const allFAicons = [
	'fas fa-ad',
	'fas fa-address-book',
	'fas fa-address-card',
	'fas fa-adjust',
	'fas fa-air-freshener',
	'fas fa-align-center',
	'fas fa-align-justify',
	'fas fa-align-left',
	'fas fa-align-right',
	'fas fa-allergies',
	'fas fa-ambulance',
	'fas fa-american-sign-language-interpreting',
	'fas fa-anchor',
	'fas fa-angle-double-down',
	'fas fa-angle-double-left',
	'fas fa-angle-double-right',
	'fas fa-angle-double-up',
	'fas fa-angle-down',
	'fas fa-angle-left',
	'fas fa-angle-right',
	'fas fa-angle-up',
	'fas fa-angry',
	'fas fa-ankh',
	'fas fa-apple-alt',
	'fas fa-archive',
	'fas fa-archway',
	'fas fa-arrow-alt-circle-down',
	'fas fa-arrow-alt-circle-left',
	'fas fa-arrow-alt-circle-right',
	'fas fa-arrow-alt-circle-up',
	'fas fa-arrow-circle-down',
	'fas fa-arrow-circle-left',
	'fas fa-arrow-circle-right',
	'fas fa-arrow-circle-up',
	'fas fa-arrow-down',
	'fas fa-arrow-left',
	'fas fa-arrow-right',
	'fas fa-arrow-up',
	'fas fa-arrows-alt',
	'fas fa-arrows-alt-h',
	'fas fa-arrows-alt-v',
	'fas fa-assistive-listening-systems',
	'fas fa-asterisk',
	'fas fa-at',
	'fas fa-atlas',
	'fas fa-atom',
	'fas fa-audio-description',
	'fas fa-award',
	'fas fa-baby',
	'fas fa-baby-carriage',
	'fas fa-backspace',
	'fas fa-backward',
	'fas fa-bacon',
	'fas fa-bahai',
	'fas fa-balance-scale',
	'fas fa-balance-scale-left',
	'fas fa-balance-scale-right',
	'fas fa-ban',
	'fas fa-band-aid',
	'fas fa-barcode',
	'fas fa-bars',
	'fas fa-baseball-ball',
	'fas fa-basketball-ball',
	'fas fa-bath',
	'fas fa-battery-empty',
	'fas fa-battery-full',
	'fas fa-battery-half',
	'fas fa-battery-quarter',
	'fas fa-battery-three-quarters',
	'fas fa-bed',
	'fas fa-beer',
	'fas fa-bell',
	'fas fa-bell-slash',
	'fas fa-bezier-curve',
	'fas fa-bible',
	'fas fa-bicycle',
	'fas fa-biking',
	'fas fa-binoculars',
	'fas fa-biohazard',
	'fas fa-birthday-cake',
	'fas fa-blender',
	'fas fa-blender-phone',
	'fas fa-blind',
	'fas fa-blog',
	'fas fa-bold',
	'fas fa-bolt',
	'fas fa-bomb',
	'fas fa-bone',
	'fas fa-bong',
	'fas fa-book',
	'fas fa-book-dead',
	'fas fa-book-medical',
	'fas fa-book-open',
	'fas fa-book-reader',
	'fas fa-bookmark',
	'fas fa-border-all',
	'fas fa-border-none',
	'fas fa-border-style',
	'fas fa-bowling-ball',
	'fas fa-box',
	'fas fa-box-open',
	'fas fa-boxes',
	'fas fa-braille',
	'fas fa-brain',
	'fas fa-bread-slice',
	'fas fa-briefcase',
	'fas fa-briefcase-medical',
	'fas fa-broadcast-tower',
	'fas fa-broom',
	'fas fa-brush',
	'fas fa-bug',
	'fas fa-building',
	'fas fa-bullhorn',
	'fas fa-bullseye',
	'fas fa-burn',
	'fas fa-bus',
	'fas fa-bus-alt',
	'fas fa-business-time',
	'fas fa-calculator',
	'fas fa-calendar',
	'fas fa-calendar-alt',
	'fas fa-calendar-check',
	'fas fa-calendar-day',
	'fas fa-calendar-minus',
	'fas fa-calendar-plus',
	'fas fa-calendar-times',
	'fas fa-calendar-week',
	'fas fa-camera',
	'fas fa-camera-retro',
	'fas fa-campground',
	'fas fa-candy-cane',
	'fas fa-cannabis',
	'fas fa-capsules',
	'fas fa-car',
	'fas fa-car-alt',
	'fas fa-car-battery',
	'fas fa-car-crash',
	'fas fa-car-side',
	'fas fa-caravan',
	'fas fa-caret-down',
	'fas fa-caret-left',
	'fas fa-caret-right',
	'fas fa-caret-square-down',
	'fas fa-caret-square-left',
	'fas fa-caret-square-right',
	'fas fa-caret-square-up',
	'fas fa-caret-up',
	'fas fa-carrot',
	'fas fa-cart-arrow-down',
	'fas fa-cart-plus',
	'fas fa-cash-register',
	'fas fa-cat',
	'fas fa-certificate',
	'fas fa-chair',
	'fas fa-chalkboard',
	'fas fa-chalkboard-teacher',
	'fas fa-charging-station',
	'fas fa-chart-area',
	'fas fa-chart-bar',
	'fas fa-chart-line',
	'fas fa-chart-pie',
	'fas fa-check',
	'fas fa-check-circle',
	'fas fa-check-double',
	'fas fa-check-square',
	'fas fa-cheese',
	'fas fa-chess',
	'fas fa-chess-bishop',
	'fas fa-chess-board',
	'fas fa-chess-king',
	'fas fa-chess-knight',
	'fas fa-chess-pawn',
	'fas fa-chess-queen',
	'fas fa-chess-rook',
	'fas fa-chevron-circle-down',
	'fas fa-chevron-circle-left',
	'fas fa-chevron-circle-right',
	'fas fa-chevron-circle-up',
	'fas fa-chevron-down',
	'fas fa-chevron-left',
	'fas fa-chevron-right',
	'fas fa-chevron-up',
	'fas fa-child',
	'fas fa-church',
	'fas fa-circle',
	'fas fa-circle-notch',
	'fas fa-city',
	'fas fa-clinic-medical',
	'fas fa-clipboard',
	'fas fa-clipboard-check',
	'fas fa-clipboard-list',
	'fas fa-clock',
	'fas fa-clone',
	'fas fa-closed-captioning',
	'fas fa-cloud',
	'fas fa-cloud-download-alt',
	'fas fa-cloud-meatball',
	'fas fa-cloud-moon',
	'fas fa-cloud-moon-rain',
	'fas fa-cloud-rain',
	'fas fa-cloud-showers-heavy',
	'fas fa-cloud-sun',
	'fas fa-cloud-sun-rain',
	'fas fa-cloud-upload-alt',
	'fas fa-cocktail',
	'fas fa-code',
	'fas fa-code-branch',
	'fas fa-coffee',
	'fas fa-cog',
	'fas fa-cogs',
	'fas fa-coins',
	'fas fa-columns',
	'fas fa-comment',
	'fas fa-comment-alt',
	'fas fa-comment-dollar',
	'fas fa-comment-dots',
	'fas fa-comment-medical',
	'fas fa-comment-slash',
	'fas fa-comments',
	'fas fa-comments-dollar',
	'fas fa-compact-disc',
	'fas fa-compass',
	'fas fa-compress',
	'fas fa-compress-alt',
	'fas fa-compress-arrows-alt',
	'fas fa-concierge-bell',
	'fas fa-cookie',
	'fas fa-cookie-bite',
	'fas fa-copy',
	'fas fa-copyright',
	'fas fa-couch',
	'fas fa-credit-card',
	'fas fa-crop',
	'fas fa-crop-alt',
	'fas fa-cross',
	'fas fa-crosshairs',
	'fas fa-crow',
	'fas fa-crown',
	'fas fa-crutch',
	'fas fa-cube',
	'fas fa-cubes',
	'fas fa-cut',
	'fas fa-database',
	'fas fa-deaf',
	'fas fa-democrat',
	'fas fa-desktop',
	'fas fa-dharmachakra',
	'fas fa-diagnoses',
	'fas fa-dice',
	'fas fa-dice-d20',
	'fas fa-dice-d6',
	'fas fa-dice-five',
	'fas fa-dice-four',
	'fas fa-dice-one',
	'fas fa-dice-six',
	'fas fa-dice-three',
	'fas fa-dice-two',
	'fas fa-digital-tachograph',
	'fas fa-directions',
	'fas fa-divide',
	'fas fa-dizzy',
	'fas fa-dna',
	'fas fa-dog',
	'fas fa-dollar-sign',
	'fas fa-dolly',
	'fas fa-dolly-flatbed',
	'fas fa-donate',
	'fas fa-door-closed',
	'fas fa-door-open',
	'fas fa-dot-circle',
	'fas fa-dove',
	'fas fa-download',
	'fas fa-drafting-compass',
	'fas fa-dragon',
	'fas fa-draw-polygon',
	'fas fa-drum',
	'fas fa-drum-steelpan',
	'fas fa-drumstick-bite',
	'fas fa-dumbbell',
	'fas fa-dumpster',
	'fas fa-dumpster-fire',
	'fas fa-dungeon',
	'fas fa-edit',
	'fas fa-egg',
	'fas fa-eject',
	'fas fa-ellipsis-h',
	'fas fa-ellipsis-v',
	'fas fa-envelope',
	'fas fa-envelope-open',
	'fas fa-envelope-open-text',
	'fas fa-envelope-square',
	'fas fa-equals',
	'fas fa-eraser',
	'fas fa-ethernet',
	'fas fa-euro-sign',
	'fas fa-exchange-alt',
	'fas fa-exclamation',
	'fas fa-exclamation-circle',
	'fas fa-exclamation-triangle',
	'fas fa-expand',
	'fas fa-expand-alt',
	'fas fa-expand-arrows-alt',
	'fas fa-external-link-alt',
	'fas fa-external-link-square-alt',
	'fas fa-eye',
	'fas fa-eye-dropper',
	'fas fa-eye-slash',
	'fas fa-fan',
	'fas fa-fast-backward',
	'fas fa-fast-forward',
	'fas fa-fax',
	'fas fa-feather',
	'fas fa-feather-alt',
	'fas fa-female',
	'fas fa-fighter-jet',
	'fas fa-file',
	'fas fa-file-alt',
	'fas fa-file-archive',
	'fas fa-file-audio',
	'fas fa-file-code',
	'fas fa-file-contract',
	'fas fa-file-csv',
	'fas fa-file-download',
	'fas fa-file-excel',
	'fas fa-file-export',
	'fas fa-file-image',
	'fas fa-file-import',
	'fas fa-file-invoice',
	'fas fa-file-invoice-dollar',
	'fas fa-file-medical',
	'fas fa-file-medical-alt',
	'fas fa-file-pdf',
	'fas fa-file-powerpoint',
	'fas fa-file-prescription',
	'fas fa-file-signature',
	'fas fa-file-upload',
	'fas fa-file-video',
	'fas fa-file-word',
	'fas fa-fill',
	'fas fa-fill-drip',
	'fas fa-film',
	'fas fa-filter',
	'fas fa-fingerprint',
	'fas fa-fire',
	'fas fa-fire-alt',
	'fas fa-fire-extinguisher',
	'fas fa-first-aid',
	'fas fa-fish',
	'fas fa-fist-raised',
	'fas fa-flag',
	'fas fa-flag-checkered',
	'fas fa-flag-usa',
	'fas fa-flask',
	'fas fa-flushed',
	'fas fa-folder',
	'fas fa-folder-minus',
	'fas fa-folder-open',
	'fas fa-folder-plus',
	'fas fa-font',
	'fas fa-football-ball',
	'fas fa-forward',
	'fas fa-frog',
	'fas fa-frown',
	'fas fa-frown-open',
	'fas fa-funnel-dollar',
	'fas fa-futbol',
	'fas fa-gamepad',
	'fas fa-gas-pump',
	'fas fa-gavel',
	'fas fa-gem',
	'fas fa-genderless',
	'fas fa-ghost',
	'fas fa-gift',
	'fas fa-gifts',
	'fas fa-glass-cheers',
	'fas fa-glass-martini',
	'fas fa-glass-martini-alt',
	'fas fa-glass-whiskey',
	'fas fa-glasses',
	'fas fa-globe',
	'fas fa-globe-africa',
	'fas fa-globe-americas',
	'fas fa-globe-asia',
	'fas fa-globe-europe',
	'fas fa-golf-ball',
	'fas fa-gopuram',
	'fas fa-graduation-cap',
	'fas fa-greater-than',
	'fas fa-greater-than-equal',
	'fas fa-grimace',
	'fas fa-grin',
	'fas fa-grin-alt',
	'fas fa-grin-beam',
	'fas fa-grin-beam-sweat',
	'fas fa-grin-hearts',
	'fas fa-grin-squint',
	'fas fa-grin-squint-tears',
	'fas fa-grin-stars',
	'fas fa-grin-tears',
	'fas fa-grin-tongue',
	'fas fa-grin-tongue-squint',
	'fas fa-grin-tongue-wink',
	'fas fa-grin-wink',
	'fas fa-grip-horizontal',
	'fas fa-grip-lines',
	'fas fa-grip-lines-vertical',
	'fas fa-grip-vertical',
	'fas fa-guitar',
	'fas fa-h-square',
	'fas fa-hamburger',
	'fas fa-hammer',
	'fas fa-hamsa',
	'fas fa-hand-holding',
	'fas fa-hand-holding-heart',
	'fas fa-hand-holding-usd',
	'fas fa-hand-lizard',
	'fas fa-hand-middle-finger',
	'fas fa-hand-paper',
	'fas fa-hand-peace',
	'fas fa-hand-point-down',
	'fas fa-hand-point-left',
	'fas fa-hand-point-right',
	'fas fa-hand-point-up',
	'fas fa-hand-pointer',
	'fas fa-hand-rock',
	'fas fa-hand-scissors',
	'fas fa-hand-spock',
	'fas fa-hands',
	'fas fa-hands-helping',
	'fas fa-handshake',
	'fas fa-hanukiah',
	'fas fa-hard-hat',
	'fas fa-hashtag',
	'fas fa-hat-cowboy',
	'fas fa-hat-cowboy-side',
	'fas fa-hat-wizard',
	'fas fa-hdd',
	'fas fa-heading',
	'fas fa-headphones',
	'fas fa-headphones-alt',
	'fas fa-headset',
	'fas fa-heart',
	'fas fa-heart-broken',
	'fas fa-heartbeat',
	'fas fa-helicopter',
	'fas fa-highlighter',
	'fas fa-hiking',
	'fas fa-hippo',
	'fas fa-history',
	'fas fa-hockey-puck',
	'fas fa-holly-berry',
	'fas fa-home',
	'fas fa-horse',
	'fas fa-horse-head',
	'fas fa-hospital',
	'fas fa-hospital-alt',
	'fas fa-hospital-symbol',
	'fas fa-hot-tub',
	'fas fa-hotdog',
	'fas fa-hotel',
	'fas fa-hourglass',
	'fas fa-hourglass-end',
	'fas fa-hourglass-half',
	'fas fa-hourglass-start',
	'fas fa-house-damage',
	'fas fa-hryvnia',
	'fas fa-i-cursor',
	'fas fa-ice-cream',
	'fas fa-icicles',
	'fas fa-icons',
	'fas fa-id-badge',
	'fas fa-id-card',
	'fas fa-id-card-alt',
	'fas fa-igloo',
	'fas fa-image',
	'fas fa-images',
	'fas fa-inbox',
	'fas fa-indent',
	'fas fa-industry',
	'fas fa-infinity',
	'fas fa-info',
	'fas fa-info-circle',
	'fas fa-italic',
	'fas fa-jedi',
	'fas fa-joint',
	'fas fa-journal-whills',
	'fas fa-kaaba',
	'fas fa-key',
	'fas fa-keyboard',
	'fas fa-khanda',
	'fas fa-kiss',
	'fas fa-kiss-beam',
	'fas fa-kiss-wink-heart',
	'fas fa-kiwi-bird',
	'fas fa-landmark',
	'fas fa-language',
	'fas fa-laptop',
	'fas fa-laptop-code',
	'fas fa-laptop-medical',
	'fas fa-laugh',
	'fas fa-laugh-beam',
	'fas fa-laugh-squint',
	'fas fa-laugh-wink',
	'fas fa-layer-group',
	'fas fa-leaf',
	'fas fa-lemon',
	'fas fa-less-than',
	'fas fa-less-than-equal',
	'fas fa-level-down-alt',
	'fas fa-level-up-alt',
	'fas fa-life-ring',
	'fas fa-lightbulb',
	'fas fa-link',
	'fas fa-lira-sign',
	'fas fa-list',
	'fas fa-list-alt',
	'fas fa-list-ol',
	'fas fa-list-ul',
	'fas fa-location-arrow',
	'fas fa-lock',
	'fas fa-lock-open',
	'fas fa-long-arrow-alt-down',
	'fas fa-long-arrow-alt-left',
	'fas fa-long-arrow-alt-right',
	'fas fa-long-arrow-alt-up',
	'fas fa-low-vision',
	'fas fa-luggage-cart',
	'fas fa-magic',
	'fas fa-magnet',
	'fas fa-mail-bulk',
	'fas fa-male',
	'fas fa-map',
	'fas fa-map-marked',
	'fas fa-map-marked-alt',
	'fas fa-map-marker',
	'fas fa-map-marker-alt',
	'fas fa-map-pin',
	'fas fa-map-signs',
	'fas fa-marker',
	'fas fa-mars',
	'fas fa-mars-double',
	'fas fa-mars-stroke',
	'fas fa-mars-stroke-h',
	'fas fa-mars-stroke-v',
	'fas fa-mask',
	'fas fa-medal',
	'fas fa-medkit',
	'fas fa-meh',
	'fas fa-meh-blank',
	'fas fa-meh-rolling-eyes',
	'fas fa-memory',
	'fas fa-menorah',
	'fas fa-mercury',
	'fas fa-meteor',
	'fas fa-microchip',
	'fas fa-microphone',
	'fas fa-microphone-alt',
	'fas fa-microphone-alt-slash',
	'fas fa-microphone-slash',
	'fas fa-microscope',
	'fas fa-minus',
	'fas fa-minus-circle',
	'fas fa-minus-square',
	'fas fa-mitten',
	'fas fa-mobile',
	'fas fa-mobile-alt',
	'fas fa-money-bill',
	'fas fa-money-bill-alt',
	'fas fa-money-bill-wave',
	'fas fa-money-bill-wave-alt',
	'fas fa-money-check',
	'fas fa-money-check-alt',
	'fas fa-monument',
	'fas fa-moon',
	'fas fa-mortar-pestle',
	'fas fa-mosque',
	'fas fa-motorcycle',
	'fas fa-mountain',
	'fas fa-mouse',
	'fas fa-mouse-pointer',
	'fas fa-mug-hot',
	'fas fa-music',
	'fas fa-network-wired',
	'fas fa-neuter',
	'fas fa-newspaper',
	'fas fa-not-equal',
	'fas fa-notes-medical',
	'fas fa-object-group',
	'fas fa-object-ungroup',
	'fas fa-oil-can',
	'fas fa-om',
	'fas fa-otter',
	'fas fa-outdent',
	'fas fa-pager',
	'fas fa-paint-brush',
	'fas fa-paint-roller',
	'fas fa-palette',
	'fas fa-pallet',
	'fas fa-paper-plane',
	'fas fa-paperclip',
	'fas fa-parachute-box',
	'fas fa-paragraph',
	'fas fa-parking',
	'fas fa-passport',
	'fas fa-pastafarianism',
	'fas fa-paste',
	'fas fa-pause',
	'fas fa-pause-circle',
	'fas fa-paw',
	'fas fa-peace',
	'fas fa-pen',
	'fas fa-pen-alt',
	'fas fa-pen-fancy',
	'fas fa-pen-nib',
	'fas fa-pen-square',
	'fas fa-pencil-alt',
	'fas fa-pencil-ruler',
	'fas fa-people-carry',
	'fas fa-pepper-hot',
	'fas fa-percent',
	'fas fa-percentage',
	'fas fa-person-booth',
	'fas fa-phone',
	'fas fa-phone-alt',
	'fas fa-phone-slash',
	'fas fa-phone-square',
	'fas fa-phone-square-alt',
	'fas fa-phone-volume',
	'fas fa-photo-video',
	'fas fa-piggy-bank',
	'fas fa-pills',
	'fas fa-pizza-slice',
	'fas fa-place-of-worship',
	'fas fa-plane',
	'fas fa-plane-arrival',
	'fas fa-plane-departure',
	'fas fa-play',
	'fas fa-play-circle',
	'fas fa-plug',
	'fas fa-plus',
	'fas fa-plus-circle',
	'fas fa-plus-square',
	'fas fa-podcast',
	'fas fa-poll',
	'fas fa-poll-h',
	'fas fa-poo',
	'fas fa-poo-storm',
	'fas fa-poop',
	'fas fa-portrait',
	'fas fa-pound-sign',
	'fas fa-power-off',
	'fas fa-pray',
	'fas fa-praying-hands',
	'fas fa-prescription',
	'fas fa-prescription-bottle',
	'fas fa-prescription-bottle-alt',
	'fas fa-print',
	'fas fa-procedures',
	'fas fa-project-diagram',
	'fas fa-puzzle-piece',
	'fas fa-qrcode',
	'fas fa-question',
	'fas fa-question-circle',
	'fas fa-quidditch',
	'fas fa-quote-left',
	'fas fa-quote-right',
	'fas fa-quran',
	'fas fa-radiation',
	'fas fa-radiation-alt',
	'fas fa-rainbow',
	'fas fa-random',
	'fas fa-receipt',
	'fas fa-record-vinyl',
	'fas fa-recycle',
	'fas fa-redo',
	'fas fa-redo-alt',
	'fas fa-registered',
	'fas fa-remove-format',
	'fas fa-reply',
	'fas fa-reply-all',
	'fas fa-republican',
	'fas fa-restroom',
	'fas fa-retweet',
	'fas fa-ribbon',
	'fas fa-ring',
	'fas fa-road',
	'fas fa-robot',
	'fas fa-rocket',
	'fas fa-route',
	'fas fa-rss',
	'fas fa-rss-square',
	'fas fa-ruble-sign',
	'fas fa-ruler',
	'fas fa-ruler-combined',
	'fas fa-ruler-horizontal',
	'fas fa-ruler-vertical',
	'fas fa-running',
	'fas fa-rupee-sign',
	'fas fa-sad-cry',
	'fas fa-sad-tear',
	'fas fa-satellite',
	'fas fa-satellite-dish',
	'fas fa-save',
	'fas fa-school',
	'fas fa-screwdriver',
	'fas fa-scroll',
	'fas fa-sd-card',
	'fas fa-search',
	'fas fa-search-dollar',
	'fas fa-search-location',
	'fas fa-search-minus',
	'fas fa-search-plus',
	'fas fa-seedling',
	'fas fa-server',
	'fas fa-shapes',
	'fas fa-share',
	'fas fa-share-alt',
	'fas fa-share-alt-square',
	'fas fa-share-square',
	'fas fa-shekel-sign',
	'fas fa-shield-alt',
	'fas fa-ship',
	'fas fa-shipping-fast',
	'fas fa-shoe-prints',
	'fas fa-shopping-bag',
	'fas fa-shopping-basket',
	'fas fa-shopping-cart',
	'fas fa-shower',
	'fas fa-shuttle-van',
	'fas fa-sign',
	'fas fa-sign-in-alt',
	'fas fa-sign-language',
	'fas fa-sign-out-alt',
	'fas fa-signal',
	'fas fa-signature',
	'fas fa-sim-card',
	'fas fa-sitemap',
	'fas fa-skating',
	'fas fa-skiing',
	'fas fa-skiing-nordic',
	'fas fa-skull',
	'fas fa-skull-crossbones',
	'fas fa-slash',
	'fas fa-sleigh',
	'fas fa-sliders-h',
	'fas fa-smile',
	'fas fa-smile-beam',
	'fas fa-smile-wink',
	'fas fa-smog',
	'fas fa-smoking',
	'fas fa-smoking-ban',
	'fas fa-sms',
	'fas fa-snowboarding',
	'fas fa-snowflake',
	'fas fa-snowman',
	'fas fa-snowplow',
	'fas fa-socks',
	'fas fa-solar-panel',
	'fas fa-sort',
	'fas fa-sort-alpha-down',
	'fas fa-sort-alpha-down-alt',
	'fas fa-sort-alpha-up',
	'fas fa-sort-alpha-up-alt',
	'fas fa-sort-amount-down',
	'fas fa-sort-amount-down-alt',
	'fas fa-sort-amount-up',
	'fas fa-sort-amount-up-alt',
	'fas fa-sort-down',
	'fas fa-sort-numeric-down',
	'fas fa-sort-numeric-down-alt',
	'fas fa-sort-numeric-up',
	'fas fa-sort-numeric-up-alt',
	'fas fa-sort-up',
	'fas fa-spa',
	'fas fa-space-shuttle',
	'fas fa-spell-check',
	'fas fa-spider',
	'fas fa-spinner',
	'fas fa-splotch',
	'fas fa-spray-can',
	'fas fa-square',
	'fas fa-square-full',
	'fas fa-square-root-alt',
	'fas fa-stamp',
	'fas fa-star',
	'fas fa-star-and-crescent',
	'fas fa-star-half',
	'fas fa-star-half-alt',
	'fas fa-star-of-david',
	'fas fa-star-of-life',
	'fas fa-step-backward',
	'fas fa-step-forward',
	'fas fa-stethoscope',
	'fas fa-sticky-note',
	'fas fa-stop',
	'fas fa-stop-circle',
	'fas fa-stopwatch',
	'fas fa-store',
	'fas fa-store-alt',
	'fas fa-stream',
	'fas fa-street-view',
	'fas fa-strikethrough',
	'fas fa-stroopwafel',
	'fas fa-subscript',
	'fas fa-subway',
	'fas fa-suitcase',
	'fas fa-suitcase-rolling',
	'fas fa-sun',
	'fas fa-superscript',
	'fas fa-surprise',
	'fas fa-swatchbook',
	'fas fa-swimmer',
	'fas fa-swimming-pool',
	'fas fa-synagogue',
	'fas fa-sync',
	'fas fa-sync-alt',
	'fas fa-syringe',
	'fas fa-table',
	'fas fa-table-tennis',
	'fas fa-tablet',
	'fas fa-tablet-alt',
	'fas fa-tablets',
	'fas fa-tachometer-alt',
	'fas fa-tag',
	'fas fa-tags',
	'fas fa-tape',
	'fas fa-tasks',
	'fas fa-taxi',
	'fas fa-teeth',
	'fas fa-teeth-open',
	'fas fa-temperature-high',
	'fas fa-temperature-low',
	'fas fa-tenge',
	'fas fa-terminal',
	'fas fa-text-height',
	'fas fa-text-width',
	'fas fa-th',
	'fas fa-th-large',
	'fas fa-th-list',
	'fas fa-theater-masks',
	'fas fa-thermometer',
	'fas fa-thermometer-empty',
	'fas fa-thermometer-full',
	'fas fa-thermometer-half',
	'fas fa-thermometer-quarter',
	'fas fa-thermometer-three-quarters',
	'fas fa-thumbs-down',
	'fas fa-thumbs-up',
	'fas fa-thumbtack',
	'fas fa-ticket-alt',
	'fas fa-times',
	'fas fa-times-circle',
	'fas fa-tint',
	'fas fa-tint-slash',
	'fas fa-tired',
	'fas fa-toggle-off',
	'fas fa-toggle-on',
	'fas fa-toilet',
	'fas fa-toilet-paper',
	'fas fa-toolbox',
	'fas fa-tools',
	'fas fa-tooth',
	'fas fa-torah',
	'fas fa-torii-gate',
	'fas fa-tractor',
	'fas fa-trademark',
	'fas fa-traffic-light',
	'fas fa-trailer',
	'fas fa-train',
	'fas fa-tram',
	'fas fa-transgender',
	'fas fa-transgender-alt',
	'fas fa-trash',
	'fas fa-trash-alt',
	'fas fa-trash-restore',
	'fas fa-trash-restore-alt',
	'fas fa-tree',
	'fas fa-trophy',
	'fas fa-truck',
	'fas fa-truck-loading',
	'fas fa-truck-monster',
	'fas fa-truck-moving',
	'fas fa-truck-pickup',
	'fas fa-tshirt',
	'fas fa-tty',
	'fas fa-tv',
	'fas fa-umbrella',
	'fas fa-umbrella-beach',
	'fas fa-underline',
	'fas fa-undo',
	'fas fa-undo-alt',
	'fas fa-universal-access',
	'fas fa-university',
	'fas fa-unlink',
	'fas fa-unlock',
	'fas fa-unlock-alt',
	'fas fa-upload',
	'fas fa-user',
	'fas fa-user-alt',
	'fas fa-user-alt-slash',
	'fas fa-user-astronaut',
	'fas fa-user-check',
	'fas fa-user-circle',
	'fas fa-user-clock',
	'fas fa-user-cog',
	'fas fa-user-edit',
	'fas fa-user-friends',
	'fas fa-user-graduate',
	'fas fa-user-injured',
	'fas fa-user-lock',
	'fas fa-user-md',
	'fas fa-user-minus',
	'fas fa-user-ninja',
	'fas fa-user-nurse',
	'fas fa-user-plus',
	'fas fa-user-secret',
	'fas fa-user-shield',
	'fas fa-user-slash',
	'fas fa-user-tag',
	'fas fa-user-tie',
	'fas fa-user-times',
	'fas fa-users',
	'fas fa-users-cog',
	'fas fa-utensil-spoon',
	'fas fa-utensils',
	'fas fa-vector-square',
	'fas fa-venus',
	'fas fa-venus-double',
	'fas fa-venus-mars',
	'fas fa-vial',
	'fas fa-vials',
	'fas fa-video',
	'fas fa-video-slash',
	'fas fa-vihara',
	'fas fa-voicemail',
	'fas fa-volleyball-ball',
	'fas fa-volume-down',
	'fas fa-volume-mute',
	'fas fa-volume-off',
	'fas fa-volume-up',
	'fas fa-vote-yea',
	'fas fa-vr-cardboard',
	'fas fa-walking',
	'fas fa-wallet',
	'fas fa-warehouse',
	'fas fa-water',
	'fas fa-wave-square',
	'fas fa-weight',
	'fas fa-weight-hanging',
	'fas fa-wheelchair',
	'fas fa-wifi',
	'fas fa-wind',
	'fas fa-window-close',
	'fas fa-window-maximize',
	'fas fa-window-minimize',
	'fas fa-window-restore',
	'fas fa-wine-bottle',
	'fas fa-wine-glass',
	'fas fa-wine-glass-alt',
	'fas fa-won-sign',
	'fas fa-wrench',
	'fas fa-x-ray',
	'fas fa-yen-sign',
	'fas fa-yin-yang',
	'far fa-address-book',
	'far fa-address-card',
	'far fa-angry',
	'far fa-arrow-alt-circle-down',
	'far fa-arrow-alt-circle-left',
	'far fa-arrow-alt-circle-right',
	'far fa-arrow-alt-circle-up',
	'far fa-bell',
	'far fa-bell-slash',
	'far fa-bookmark',
	'far fa-building',
	'far fa-calendar',
	'far fa-calendar-alt',
	'far fa-calendar-check',
	'far fa-calendar-minus',
	'far fa-calendar-plus',
	'far fa-calendar-times',
	'far fa-caret-square-down',
	'far fa-caret-square-left',
	'far fa-caret-square-right',
	'far fa-caret-square-up',
	'far fa-chart-bar',
	'far fa-check-circle',
	'far fa-check-square',
	'far fa-circle',
	'far fa-clipboard',
	'far fa-clock',
	'far fa-clone',
	'far fa-closed-captioning',
	'far fa-comment',
	'far fa-comment-alt',
	'far fa-comment-dots',
	'far fa-comments',
	'far fa-compass',
	'far fa-copy',
	'far fa-copyright',
	'far fa-credit-card',
	'far fa-dizzy',
	'far fa-dot-circle',
	'far fa-edit',
	'far fa-envelope',
	'far fa-envelope-open',
	'far fa-eye',
	'far fa-eye-slash',
	'far fa-file',
	'far fa-file-alt',
	'far fa-file-archive',
	'far fa-file-audio',
	'far fa-file-code',
	'far fa-file-excel',
	'far fa-file-image',
	'far fa-file-pdf',
	'far fa-file-powerpoint',
	'far fa-file-video',
	'far fa-file-word',
	'far fa-flag',
	'far fa-flushed',
	'far fa-folder',
	'far fa-folder-open',
	'far fa-frown',
	'far fa-frown-open',
	'far fa-futbol',
	'far fa-gem',
	'far fa-grimace',
	'far fa-grin',
	'far fa-grin-alt',
	'far fa-grin-beam',
	'far fa-grin-beam-sweat',
	'far fa-grin-hearts',
	'far fa-grin-squint',
	'far fa-grin-squint-tears',
	'far fa-grin-stars',
	'far fa-grin-tears',
	'far fa-grin-tongue',
	'far fa-grin-tongue-squint',
	'far fa-grin-tongue-wink',
	'far fa-grin-wink',
	'far fa-hand-lizard',
	'far fa-hand-paper',
	'far fa-hand-peace',
	'far fa-hand-point-down',
	'far fa-hand-point-left',
	'far fa-hand-point-right',
	'far fa-hand-point-up',
	'far fa-hand-pointer',
	'far fa-hand-rock',
	'far fa-hand-scissors',
	'far fa-hand-spock',
	'far fa-handshake',
	'far fa-hdd',
	'far fa-heart',
	'far fa-hospital',
	'far fa-hourglass',
	'far fa-id-badge',
	'far fa-id-card',
	'far fa-image',
	'far fa-images',
	'far fa-keyboard',
	'far fa-kiss',
	'far fa-kiss-beam',
	'far fa-kiss-wink-heart',
	'far fa-laugh',
	'far fa-laugh-beam',
	'far fa-laugh-squint',
	'far fa-laugh-wink',
	'far fa-lemon',
	'far fa-life-ring',
	'far fa-lightbulb',
	'far fa-list-alt',
	'far fa-map',
	'far fa-meh',
	'far fa-meh-blank',
	'far fa-meh-rolling-eyes',
	'far fa-minus-square',
	'far fa-money-bill-alt',
	'far fa-moon',
	'far fa-newspaper',
	'far fa-object-group',
	'far fa-object-ungroup',
	'far fa-paper-plane',
	'far fa-pause-circle',
	'far fa-play-circle',
	'far fa-plus-square',
	'far fa-question-circle',
	'far fa-registered',
	'far fa-sad-cry',
	'far fa-sad-tear',
	'far fa-save',
	'far fa-share-square',
	'far fa-smile',
	'far fa-smile-beam',
	'far fa-smile-wink',
	'far fa-snowflake',
	'far fa-square',
	'far fa-star',
	'far fa-star-half',
	'far fa-sticky-note',
	'far fa-stop-circle',
	'far fa-sun',
	'far fa-surprise',
	'far fa-thumbs-down',
	'far fa-thumbs-up',
	'far fa-times-circle',
	'far fa-tired',
	'far fa-trash-alt',
	'far fa-user',
	'far fa-user-circle',
	'far fa-window-close',
	'far fa-window-maximize',
	'far fa-window-minimize',
	'far fa-window-restore',
	'fab fa-500px',
	'fab fa-accessible-icon',
	'fab fa-accusoft',
	'fab fa-acquisitions-incorporated',
	'fab fa-adn',
	'fab fa-adobe',
	'fab fa-adversal',
	'fab fa-affiliatetheme',
	'fab fa-airbnb',
	'fab fa-algolia',
	'fab fa-alipay',
	'fab fa-amazon',
	'fab fa-amazon-pay',
	'fab fa-amilia',
	'fab fa-android',
	'fab fa-angellist',
	'fab fa-angrycreative',
	'fab fa-angular',
	'fab fa-app-store',
	'fab fa-app-store-ios',
	'fab fa-apper',
	'fab fa-apple',
	'fab fa-apple-pay',
	'fab fa-artstation',
	'fab fa-asymmetrik',
	'fab fa-atlassian',
	'fab fa-audible',
	'fab fa-autoprefixer',
	'fab fa-avianex',
	'fab fa-aviato',
	'fab fa-aws',
	'fab fa-bandcamp',
	'fab fa-battle-net',
	'fab fa-behance',
	'fab fa-behance-square',
	'fab fa-bimobject',
	'fab fa-bitbucket',
	'fab fa-bitcoin',
	'fab fa-bity',
	'fab fa-black-tie',
	'fab fa-blackberry',
	'fab fa-blogger',
	'fab fa-blogger-b',
	'fab fa-bluetooth',
	'fab fa-bluetooth-b',
	'fab fa-bootstrap',
	'fab fa-btc',
	'fab fa-buffer',
	'fab fa-buromobelexperte',
	'fab fa-buy-n-large',
	'fab fa-buysellads',
	'fab fa-canadian-maple-leaf',
	'fab fa-cc-amazon-pay',
	'fab fa-cc-amex',
	'fab fa-cc-apple-pay',
	'fab fa-cc-diners-club',
	'fab fa-cc-discover',
	'fab fa-cc-jcb',
	'fab fa-cc-mastercard',
	'fab fa-cc-paypal',
	'fab fa-cc-stripe',
	'fab fa-cc-visa',
	'fab fa-centercode',
	'fab fa-centos',
	'fab fa-chrome',
	'fab fa-chromecast',
	'fab fa-cloudscale',
	'fab fa-cloudsmith',
	'fab fa-cloudversify',
	'fab fa-codepen',
	'fab fa-codiepie',
	'fab fa-confluence',
	'fab fa-connectdevelop',
	'fab fa-contao',
	'fab fa-cotton-bureau',
	'fab fa-cpanel',
	'fab fa-creative-commons',
	'fab fa-creative-commons-by',
	'fab fa-creative-commons-nc',
	'fab fa-creative-commons-nc-eu',
	'fab fa-creative-commons-nc-jp',
	'fab fa-creative-commons-nd',
	'fab fa-creative-commons-pd',
	'fab fa-creative-commons-pd-alt',
	'fab fa-creative-commons-remix',
	'fab fa-creative-commons-sa',
	'fab fa-creative-commons-sampling',
	'fab fa-creative-commons-sampling-plus',
	'fab fa-creative-commons-share',
	'fab fa-creative-commons-zero',
	'fab fa-critical-role',
	'fab fa-css3',
	'fab fa-css3-alt',
	'fab fa-cuttlefish',
	'fab fa-d-and-d',
	'fab fa-d-and-d-beyond',
	'fab fa-dailymotion',
	'fab fa-dashcube',
	'fab fa-delicious',
	'fab fa-deploydog',
	'fab fa-deskpro',
	'fab fa-dev',
	'fab fa-deviantart',
	'fab fa-dhl',
	'fab fa-diaspora',
	'fab fa-digg',
	'fab fa-digital-ocean',
	'fab fa-discord',
	'fab fa-discourse',
	'fab fa-dochub',
	'fab fa-docker',
	'fab fa-draft2digital',
	'fab fa-dribbble',
	'fab fa-dribbble-square',
	'fab fa-dropbox',
	'fab fa-drupal',
	'fab fa-dyalog',
	'fab fa-earlybirds',
	'fab fa-ebay',
	'fab fa-edge',
	'fab fa-elementor',
	'fab fa-ello',
	'fab fa-ember',
	'fab fa-empire',
	'fab fa-envira',
	'fab fa-erlang',
	'fab fa-ethereum',
	'fab fa-etsy',
	'fab fa-evernote',
	'fab fa-expeditedssl',
	'fab fa-facebook',
	'fab fa-facebook-f',
	'fab fa-facebook-messenger',
	'fab fa-facebook-square',
	'fab fa-fantasy-flight-games',
	'fab fa-fedex',
	'fab fa-fedora',
	'fab fa-figma',
	'fab fa-firefox',
	'fab fa-firefox-browser',
	'fab fa-first-order',
	'fab fa-first-order-alt',
	'fab fa-firstdraft',
	'fab fa-flickr',
	'fab fa-flipboard',
	'fab fa-fly',
	'fab fa-font-awesome',
	'fab fa-font-awesome-alt',
	'fab fa-font-awesome-flag',
	'fab fa-fonticons',
	'fab fa-fonticons-fi',
	'fab fa-fort-awesome',
	'fab fa-fort-awesome-alt',
	'fab fa-forumbee',
	'fab fa-foursquare',
	'fab fa-free-code-camp',
	'fab fa-freebsd',
	'fab fa-fulcrum',
	'fab fa-galactic-republic',
	'fab fa-galactic-senate',
	'fab fa-get-pocket',
	'fab fa-gg',
	'fab fa-gg-circle',
	'fab fa-git',
	'fab fa-git-alt',
	'fab fa-git-square',
	'fab fa-github',
	'fab fa-github-alt',
	'fab fa-github-square',
	'fab fa-gitkraken',
	'fab fa-gitlab',
	'fab fa-gitter',
	'fab fa-glide',
	'fab fa-glide-g',
	'fab fa-gofore',
	'fab fa-goodreads',
	'fab fa-goodreads-g',
	'fab fa-google',
	'fab fa-google-drive',
	'fab fa-google-play',
	'fab fa-google-plus',
	'fab fa-google-plus-g',
	'fab fa-google-plus-square',
	'fab fa-google-wallet',
	'fab fa-gratipay',
	'fab fa-grav',
	'fab fa-gripfire',
	'fab fa-grunt',
	'fab fa-gulp',
	'fab fa-hacker-news',
	'fab fa-hacker-news-square',
	'fab fa-hackerrank',
	'fab fa-hips',
	'fab fa-hire-a-helper',
	'fab fa-hooli',
	'fab fa-hornbill',
	'fab fa-hotjar',
	'fab fa-houzz',
	'fab fa-html5',
	'fab fa-hubspot',
	'fab fa-ideal',
	'fab fa-imdb',
	'fab fa-instagram',
	'fab fa-instagram-square',
	'fab fa-intercom',
	'fab fa-internet-explorer',
	'fab fa-invision',
	'fab fa-ioxhost',
	'fab fa-itch-io',
	'fab fa-itunes',
	'fab fa-itunes-note',
	'fab fa-java',
	'fab fa-jedi-order',
	'fab fa-jenkins',
	'fab fa-jira',
	'fab fa-joget',
	'fab fa-joomla',
	'fab fa-js',
	'fab fa-js-square',
	'fab fa-jsfiddle',
	'fab fa-kaggle',
	'fab fa-keybase',
	'fab fa-keycdn',
	'fab fa-kickstarter',
	'fab fa-kickstarter-k',
	'fab fa-korvue',
	'fab fa-laravel',
	'fab fa-lastfm',
	'fab fa-lastfm-square',
	'fab fa-leanpub',
	'fab fa-less',
	'fab fa-line',
	'fab fa-linkedin',
	'fab fa-linkedin-in',
	'fab fa-linode',
	'fab fa-linux',
	'fab fa-lyft',
	'fab fa-magento',
	'fab fa-mailchimp',
	'fab fa-mandalorian',
	'fab fa-markdown',
	'fab fa-mastodon',
	'fab fa-maxcdn',
	'fab fa-mdb',
	'fab fa-medapps',
	'fab fa-medium',
	'fab fa-medium-m',
	'fab fa-medrt',
	'fab fa-meetup',
	'fab fa-megaport',
	'fab fa-mendeley',
	'fab fa-microblog',
	'fab fa-microsoft',
	'fab fa-mix',
	'fab fa-mixcloud',
	'fab fa-mixer',
	'fab fa-mizuni',
	'fab fa-modx',
	'fab fa-monero',
	'fab fa-napster',
	'fab fa-neos',
	'fab fa-nimblr',
	'fab fa-node',
	'fab fa-node-js',
	'fab fa-npm',
	'fab fa-ns8',
	'fab fa-nutritionix',
	'fab fa-odnoklassniki',
	'fab fa-odnoklassniki-square',
	'fab fa-old-republic',
	'fab fa-opencart',
	'fab fa-openid',
	'fab fa-opera',
	'fab fa-optin-monster',
	'fab fa-orcid',
	'fab fa-osi',
	'fab fa-page4',
	'fab fa-pagelines',
	'fab fa-palfed',
	'fab fa-patreon',
	'fab fa-paypal',
	'fab fa-penny-arcade',
	'fab fa-periscope',
	'fab fa-phabricator',
	'fab fa-phoenix-framework',
	'fab fa-phoenix-squadron',
	'fab fa-php',
	'fab fa-pied-piper',
	'fab fa-pied-piper-alt',
	'fab fa-pied-piper-hat',
	'fab fa-pied-piper-pp',
	'fab fa-pied-piper-square',
	'fab fa-pinterest',
	'fab fa-pinterest-p',
	'fab fa-pinterest-square',
	'fab fa-playstation',
	'fab fa-product-hunt',
	'fab fa-pushed',
	'fab fa-python',
	'fab fa-qq',
	'fab fa-quinscape',
	'fab fa-quora',
	'fab fa-r-project',
	'fab fa-raspberry-pi',
	'fab fa-ravelry',
	'fab fa-react',
	'fab fa-reacteurope',
	'fab fa-readme',
	'fab fa-rebel',
	'fab fa-red-river',
	'fab fa-reddit',
	'fab fa-reddit-alien',
	'fab fa-reddit-square',
	'fab fa-redhat',
	'fab fa-renren',
	'fab fa-replyd',
	'fab fa-researchgate',
	'fab fa-resolving',
	'fab fa-rev',
	'fab fa-rocketchat',
	'fab fa-rockrms',
	'fab fa-safari',
	'fab fa-salesforce',
	'fab fa-sass',
	'fab fa-schlix',
	'fab fa-scribd',
	'fab fa-searchengin',
	'fab fa-sellcast',
	'fab fa-sellsy',
	'fab fa-servicestack',
	'fab fa-shirtsinbulk',
	'fab fa-shopify',
	'fab fa-shopware',
	'fab fa-simplybuilt',
	'fab fa-sistrix',
	'fab fa-sith',
	'fab fa-sketch',
	'fab fa-skyatlas',
	'fab fa-skype',
	'fab fa-slack',
	'fab fa-slack-hash',
	'fab fa-slideshare',
	'fab fa-snapchat',
	'fab fa-snapchat-ghost',
	'fab fa-snapchat-square',
	'fab fa-soundcloud',
	'fab fa-sourcetree',
	'fab fa-speakap',
	'fab fa-speaker-deck',
	'fab fa-spotify',
	'fab fa-squarespace',
	'fab fa-stack-exchange',
	'fab fa-stack-overflow',
	'fab fa-stackpath',
	'fab fa-staylinked',
	'fab fa-steam',
	'fab fa-steam-square',
	'fab fa-steam-symbol',
	'fab fa-sticker-mule',
	'fab fa-strava',
	'fab fa-stripe',
	'fab fa-stripe-s',
	'fab fa-studiovinari',
	'fab fa-stumbleupon',
	'fab fa-stumbleupon-circle',
	'fab fa-superpowers',
	'fab fa-supple',
	'fab fa-suse',
	'fab fa-swift',
	'fab fa-symfony',
	'fab fa-teamspeak',
	'fab fa-telegram',
	'fab fa-telegram-plane',
	'fab fa-tencent-weibo',
	'fab fa-the-red-yeti',
	'fab fa-themeco',
	'fab fa-themeisle',
	'fab fa-think-peaks',
	'fab fa-trade-federation',
	'fab fa-trello',
	'fab fa-tripadvisor',
	'fab fa-tumblr',
	'fab fa-tumblr-square',
	'fab fa-twitch',
	'fab fa-twitter',
	'fab fa-twitter-square',
	'fab fa-typo3',
	'fab fa-uber',
	'fab fa-ubuntu',
	'fab fa-uikit',
	'fab fa-umbraco',
	'fab fa-uniregistry',
	'fab fa-unity',
	'fab fa-untappd',
	'fab fa-ups',
	'fab fa-usb',
	'fab fa-usps',
	'fab fa-ussunnah',
	'fab fa-vaadin',
	'fab fa-viacoin',
	'fab fa-viadeo',
	'fab fa-viadeo-square',
	'fab fa-viber',
	'fab fa-vimeo',
	'fab fa-vimeo-square',
	'fab fa-vimeo-v',
	'fab fa-vine',
	'fab fa-vk',
	'fab fa-vnv',
	'fab fa-vuejs',
	'fab fa-waze',
	'fab fa-weebly',
	'fab fa-weibo',
	'fab fa-weixin',
	'fab fa-whatsapp',
	'fab fa-whatsapp-square',
	'fab fa-whmcs',
	'fab fa-wikipedia-w',
	'fab fa-windows',
	'fab fa-wix',
	'fab fa-wizards-of-the-coast',
	'fab fa-wolf-pack-battalion',
	'fab fa-wordpress',
	'fab fa-wordpress-simple',
	'fab fa-wpbeginner',
	'fab fa-wpexplorer',
	'fab fa-wpforms',
	'fab fa-wpressr',
	'fab fa-xbox',
	'fab fa-xing',
	'fab fa-xing-square',
	'fab fa-y-combinator',
	'fab fa-yahoo',
	'fab fa-yammer',
	'fab fa-yandex',
	'fab fa-yandex-international',
	'fab fa-yarn',
	'fab fa-yelp',
	'fab fa-yoast',
	'fab fa-youtube',
	'fab fa-youtube-square',
	'fab fa-zhihu',
];

let allMaticons = [
	'search',
	'home',
	'settings',
	'done',
	'account_circle',
	'check_circle',
	'face',
	'info',
	'fingerprint',
	'delete',
	'favorite',
	'shopping_cart',
	'visibility',
	'logout',
	'favorite_border',
	'description',
	'help_outline',
	'lock',
	'language',
	'schedule',
	'thumb_up',
	'manage_accounts',
	'verified',
	'lightbulb',
	'event',
	'dashboard',
	'list',
	'filter_alt',
	'calendar_today',
	'login',
	'trending_up',
	'question_answer',
	'account_balance',
	'visibility_off',
	'open_in_new',
	'check_circle_outline',
	'paid',
	'shopping_bag',
	'date_range',
	'help',
	'highlight_off',
	'arrow_right_alt',
	'android',
	'task_alt',
	'article',
	'pets',
	'star_rate',
	'build',
	'credit_card',
	'perm_identity',
	'flutter_dash',
	'verified_user',
	'history',
	'fact_check',
	'assignment',
	'analytics',
	'report_problem',
	'delete_outline',
	'work',
	'accessibility',
	'code',
	'savings',
	'autorenew',
	'print',
	'add_shopping_cart',
	'account_balance_wallet',
	'today',
	'grade',
	'view_list',
	'store',
	'delete_forever',
	'lock_open',
	'admin_panel_settings',
	'room',
	'watch_later',
	'power_settings_new',
	'explore',
	'update',
	'launch',
	'bug_report',
	'done_outline',
	'pan_tool',
	'done_all',
	'thumb_up_off_alt',
	'3d_rotation',
	'account_box',
	'receipt',
	'view_in_ar',
	'contact_support',
	'bookmark',
	'shopping_basket',
	'touch_app',
	'feedback',
	'accessibility_new',
	'note_add',
	'timeline',
	'supervisor_account',
	'reorder',
	'payment',
	'bookmark_border',
	'zoom_in',
	'drag_indicator',
	'assessment',
	'flight_takeoff',
	'exit_to_app',
	'leaderboard',
	'add_task',
	'stars',
	'open_in_full',
	'pending_actions',
	'pending',
	'preview',
	'alarm',
	'dns',
	'work_outline',
	'gavel',
	'nightlight_round',
	'assignment_ind',
	'record_voice_over',
	'book',
	'card_giftcard',
	'get_app',
	'cached',
	'published_with_changes',
	'supervised_user_circle',
	'extension',
	'assignment_turned_in',
	'label',
	'swap_horiz',
	'translate',
	'contact_page',
	'thumb_down',
	'sync_alt',
	'privacy_tip',
	'minimize',
	'trending_flat',
	'hourglass_empty',
	'loyalty',
	'group_work',
	'help_center',
	'announcement',
	'space_dashboard',
	'dashboard_customize',
	'euro_symbol',
	'rule',
	'settings_applications',
	'arrow_circle_up',
	'api',
	'grading',
	'sticky_note_2',
	'support',
	'sensors',
	'compare_arrows',
	'source',
	'close_fullscreen',
	'copyright',
	'query_builder',
	'input',
	'track_changes',
	'book_online',
	'backup',
	'view_headline',
	'g_translate',
	'settings_phone',
	'subject',
	'edit_calendar',
	'bookmarks',
	'build_circle',
	'restore',
	'find_in_page',
	'table_view',
	'dangerous',
	'redeem',
	'model_training',
	'perm_media',
	'swap_vert',
	'https',
	'open_with',
	'arrow_circle_down',
	'swipe',
	'circle_notifications',
	'trending_down',
	'accessible',
	'label_important',
	'disabled_by_default',
	'toc',
	'invert_colors',
	'pageview',
	'zoom_out',
	'wysiwyg',
	'perm_phone_msg',
	'settings_accessibility',
	'integration_instructions',
	'file_present',
	'card_membership',
	'speaker_notes',
	'change_history',
	'offline_bolt',
	'thumbs_up_down',
	'perm_contact_calendar',
	'view_module',
	'ads_click',
	'bookmark_add',
	'opacity',
	'upgrade',
	'calendar_view_month',
	'production_quantity_limits',
	'alarm_on',
	'donut_large',
	'add_to_drive',
	'no_accounts',
	'aspect_ratio',
	'expand',
	'saved_search',
	'class',
	'mediation',
	'thumb_down_off_alt',
	'important_devices',
	'theaters',
	'commute',
	'accessible_forward',
	'schedule_send',
	'settings_ethernet',
	'settings_backup_restore',
	'maximize',
	'youtube_searched_for',
	'segment',
	'addchart',
	'not_started',
	'bookmark_added',
	'anchor',
	'system_update_alt',
	'flaky',
	'mark_as_unread',
	'open_in_browser',
	'settings_input_antenna',
	'contactless',
	'turned_in',
	'history_toggle_off',
	'view_column',
	'tour',
	'fit_screen',
	'settings_voice',
	'pregnant_woman',
	'view_week',
	'flight_land',
	'shop',
	'unpublished',
	'camera_enhance',
	'view_agenda',
	'view_carousel',
	'settings_remote',
	'highlight_alt',
	'offline_pin',
	'tab',
	'toll',
	'hide_source',
	'search_off',
	'hourglass_full',
	'assignment_late',
	'lock_clock',
	'turned_in_not',
	'donut_small',
	'next_plan',
	'settings_input_component',
	'online_prediction',
	'remove_shopping_cart',
	'all_inbox',
	'outlet',
	'plagiarism',
	'dynamic_form',
	'rowing',
	'view_sidebar',
	'event_seat',
	'edit_off',
	'markunread_mailbox',
	'settings_power',
	'gif',
	'restore_from_trash',
	'try',
	'swap_horizontal_circle',
	'smart_button',
	'alarm_add',
	'settings_input_composite',
	'request_page',
	'card_travel',
	'assignment_return',
	'play_for_work',
	'settings_bluetooth',
	'settings_overscan',
	'polymer',
	'wifi_protected_setup',
	'view_quilt',
	'compress',
	'vertical_split',
	'settings_brightness',
	'http',
	'outbox',
	'calendar_view_week',
	'find_replace',
	'remove_done',
	'chrome_reader_mode',
	'calendar_view_day',
	'spellcheck',
	'tips_and_updates',
	'comment_bank',
	'quickreply',
	'view_day',
	'settings_cell',
	'outbound',
	'batch_prediction',
	'hotel_class',
	'new_label',
	'picture_in_picture',
	'view_stream',
	'code_off',
	'bookmark_remove',
	'restore_page',
	'settings_input_hdmi',
	'send_and_archive',
	'credit_card_off',
	'assignment_returned',
	'backup_table',
	'line_style',
	'alarm_off',
	'line_weight',
	'perm_scan_wifi',
	'swap_vertical_circle',
	'app_blocking',
	'flip_to_front',
	'cancel_schedule_send',
	'eject',
	'perm_data_setting',
	'sensors_off',
	'speaker_notes_off',
	'horizontal_split',
	'shop_two',
	'generating_tokens',
	'perm_device_information',
	'settings_input_svideo',
	'hourglass_disabled',
	'picture_in_picture_alt',
	'open_in_new_off',
	'voice_over_off',
	'work_off',
	'subtitles_off',
	'update_disabled',
	'view_array',
	'all_out',
	'tab_unselected',
	'data_exploration',
	'free_cancellation',
	'flip_to_back',
	'shop_2',
	'explore_off',
	'label_off',
	'text_rotation_none',
	'perm_camera_mic',
	'not_accessible',
	'rounded_corner',
	'private_connectivity',
	'disabled_visible',
	'text_rotate_vertical',
	'extension_off',
	'text_rotation_angleup',
	'pin_invoke',
	'text_rotation_down',
	'text_rotation_angledown',
	'pin_end',
	'text_rotate_up',
	'menu',
	'close',
	'expand_more',
	'arrow_back',
	'chevron_right',
	'arrow_forward_ios',
	'arrow_back_ios',
	'arrow_drop_down',
	'cancel',
	'more_vert',
	'arrow_forward',
	'expand_less',
	'chevron_left',
	'more_horiz',
	'check',
	'refresh',
	'apps',
	'arrow_back_ios_new',
	'arrow_upward',
	'payments',
	'east',
	'campaign',
	'arrow_right',
	'menu_open',
	'arrow_downward',
	'double_arrow',
	'fullscreen',
	'unfold_more',
	'maps_home_work',
	'arrow_drop_up',
	'west',
	'south',
	'arrow_left',
	'arrow_drop_down_circle',
	'home_work',
	'first_page',
	'fullscreen_exit',
	'north',
	'north_east',
	'last_page',
	'subdirectory_arrow_right',
	'unfold_less',
	'legend_toggle',
	'assistant_direction',
	'subdirectory_arrow_left',
	'app_settings_alt',
	'waterfall_chart',
	'south_east',
	'north_west',
	'switch_left',
	'south_west',
	'switch_right',
	'pivot_table_chart',
	'offline_share',
	'person',
	'facebook',
	'notifications',
	'groups',
	'share',
	'people',
	'school',
	'person_outline',
	'public',
	'emoji_events',
	'person_add',
	'group',
	'engineering',
	'notifications_active',
	'construction',
	'people_alt',
	'psychology',
	'health_and_safety',
	'emoji_emotions',
	'coronavirus',
	'travel_explore',
	'group_add',
	'notifications_none',
	'sentiment_satisfied',
	'thumb_up_alt',
	'emoji_objects',
	'sentiment_very_satisfied',
	'precision_manufacturing',
	'science',
	'military_tech',
	'ios_share',
	'sports_esports',
	'location_city',
	'cake',
	'person_add_alt',
	'sentiment_dissatisfied',
	'self_improvement',
	'history_edu',
	'emoji_people',
	'sentiment_very_dissatisfied',
	'catching_pokemon',
	'mood',
	'female',
	'recommend',
	'poll',
	'masks',
	'domain',
	'person_remove',
	'sports_soccer',
	'male',
	'whatshot',
	'people_outline',
	'connect_without_contact',
	'hiking',
	'person_add_alt_1',
	'sentiment_neutral',
	'architecture',
	'person_off',
	'emoji_nature',
	'notifications_off',
	'mood_bad',
	'emoji_symbols',
	'switch_account',
	'luggage',
	'nights_stay',
	'recycling',
	'thumb_down_alt',
	'sports_kabaddi',
	'sports_basketball',
	'back_hand',
	'notification_add',
	'water_drop',
	'emoji_flags',
	'waving_hand',
	'social_distance',
	'king_bed',
	'front_hand',
	'emoji_food_beverage',
	'sick',
	'sports_tennis',
	'clean_hands',
	'outdoor_grill',
	'deck',
	'sports',
	'plus_one',
	'emoji_transportation',
	'transgender',
	'sanitizer',
	'elderly',
	'fireplace',
	'reduce_capacity',
	'add_reaction',
	'sports_baseball',
	'follow_the_signs',
	'sports_motorsports',
	'add_moderator',
	'real_estate_agent',
	'edit_notifications',
	'kayaking',
	'sports_volleyball',
	'surfing',
	'piano',
	'sports_football',
	'sports_handball',
	'6_ft_apart',
	'skateboarding',
	'downhill_skiing',
	'pages',
	'single_bed',
	'public_off',
	'remove_moderator',
	'personal_injury',
	'paragliding',
	'nordic_walking',
	'safety_divider',
	'person_remove_alt_1',
	'sports_cricket',
	'snowboarding',
	'sports_mma',
	'compost',
	'notifications_paused',
	'party_mode',
	'kitesurfing',
	'sports_golf',
	'group_off',
	'ice_skating',
	'snowshoeing',
	'sports_rugby',
	'sports_hockey',
	'sledding',
	'cruelty_free',
	'no_luggage',
	'piano_off',
	'add',
	'add_circle_outline',
	'add_circle',
	'send',
	'content_copy',
	'clear',
	'save',
	'link',
	'mail',
	'filter_list',
	'remove',
	'inventory_2',
	'insights',
	'create',
	'bolt',
	'remove_circle_outline',
	'inventory',
	'sort',
	'remove_circle',
	'flag',
	'reply',
	'add_box',
	'push_pin',
	'block',
	'calculate',
	'content_paste',
	'how_to_reg',
	'undo',
	'file_copy',
	'report',
	'shield',
	'archive',
	'save_alt',
	'backspace',
	'policy',
	'change_circle',
	'tag',
	'content_cut',
	'forward',
	'redo',
	'biotech',
	'inbox',
	'stacked_bar_chart',
	'drafts',
	'ballot',
	'outlined_flag',
	'link_off',
	'markunread',
	'stream',
	'square_foot',
	'delete_sweep',
	'report_gmailerrorred',
	'dynamic_feed',
	'waves',
	'add_link',
	'where_to_vote',
	'move_to_inbox',
	'copy_all',
	'reply_all',
	'unarchive',
	'low_priority',
	'how_to_vote',
	'select_all',
	'weekend',
	'text_format',
	'upcoming',
	'gesture',
	'font_download',
	'attribution',
	'next_week',
	'content_paste_off',
	'report_off',
	'font_download_off',
	'email',
	'location_on',
	'call',
	'phone',
	'business',
	'chat',
	'mail_outline',
	'vpn_key',
	'qr_code_scanner',
	'list_alt',
	'chat_bubble_outline',
	'alternate_email',
	'chat_bubble',
	'forum',
	'sentiment_satisfied_alt',
	'textsms',
	'qr_code_2',
	'contact_mail',
	'person_search',
	'message',
	'qr_code',
	'contacts',
	'comment',
	'app_registration',
	'live_help',
	'rss_feed',
	'contact_phone',
	'import_contacts',
	'import_export',
	'forward_to_inbox',
	'hourglass_bottom',
	'hourglass_top',
	'mark_email_read',
	'read_more',
	'document_scanner',
	'call_end',
	'mark_email_unread',
	'more_time',
	'dialpad',
	'clear_all',
	'phone_enabled',
	'mark_chat_unread',
	'screen_share',
	'3p',
	'present_to_all',
	'cancel_presentation',
	'stay_current_portrait',
	'unsubscribe',
	'call_made',
	'call_split',
	'mark_chat_read',
	'phonelink_ring',
	'duo',
	'domain_verification',
	'stay_primary_portrait',
	'phonelink_lock',
	'add_ic_call',
	'location_off',
	'ring_volume',
	'phone_disabled',
	'swap_calls',
	'phonelink_setup',
	'call_received',
	'mobile_screen_share',
	'cell_wifi',
	'call_merge',
	'voicemail',
	'speaker_phone',
	'person_add_disabled',
	'domain_disabled',
	'call_missed_outgoing',
	'portable_wifi_off',
	'call_missed',
	'phonelink_erase',
	'desktop_access_disabled',
	'pause_presentation',
	'rtt',
	'sip',
	'stop_screen_share',
	'stay_current_landscape',
	'invert_colors_off',
	'wifi_calling',
	'dialer_sip',
	'nat',
	'stay_primary_landscape',
	'print_disabled',
	'no_sim',
	'edit',
	'navigate_next',
	'photo_camera',
	'image',
	'picture_as_pdf',
	'tune',
	'circle',
	'receipt_long',
	'timer',
	'auto_stories',
	'auto_awesome',
	'navigate_before',
	'add_a_photo',
	'collections',
	'palette',
	'remove_red_eye',
	'music_note',
	'wb_sunny',
	'brush',
	'add_photo_alternate',
	'flash_on',
	'camera_alt',
	'auto_fix_high',
	'euro',
	'audiotrack',
	'camera',
	'looks_one',
	'style',
	'control_point',
	'straighten',
	'photo_library',
	'portrait',
	'adjust',
	'color_lens',
	'landscape',
	'grid_on',
	'video_camera_front',
	'filter_vintage',
	'image_search',
	'blur_on',
	'collections_bookmark',
	'crop_square',
	'timelapse',
	'lens',
	'rotate_right',
	'slideshow',
	'panorama_fish_eye',
	'filter_drama',
	'auto_awesome_motion',
	'healing',
	'looks_two',
	'crop',
	'crop_free',
	'wb_incandescent',
	'tag_faces',
	'looks_3',
	'dehaze',
	'face_retouching_natural',
	'assistant',
	'rotate_left',
	'broken_image',
	'nature_people',
	'wb_cloudy',
	'colorize',
	'center_focus_strong',
	'brightness_4',
	'auto_awesome_mosaic',
	'flare',
	'photo',
	'brightness_5',
	'crop_original',
	'compare',
	'cases',
	'grain',
	'flash_off',
	'filter_none',
	'flip_camera_android',
	'brightness_6',
	'filter_center_focus',
	'movie_creation',
	'details',
	'brightness_1',
	'loupe',
	'filter_1',
	'texture',
	'nature',
	'animation',
	'panorama',
	'flip_camera_ios',
	'add_to_photos',
	'brightness_7',
	'looks_4',
	'flip',
	'image_not_supported',
	'auto_fix_normal',
	'filter',
	'photo_size_select_actual',
	'bedtime',
	'leak_add',
	'crop_din',
	'view_comfy',
	'transform',
	'movie_filter',
	'center_focus_weak',
	'motion_photos_on',
	'timer_off',
	'video_camera_back',
	'shutter_speed',
	'thermostat_auto',
	'photo_camera_front',
	'mic_external_on',
	'gradient',
	'control_point_duplicate',
	'filter_tilt_shift',
	'music_off',
	'looks_5',
	'rotate_90_degrees_ccw',
	'photo_album',
	'view_compact',
	'filter_2',
	'assistant_photo',
	'photo_filter',
	'exposure_plus_1',
	'blur_circular',
	'motion_photos_auto',
	'hide_image',
	'looks',
	'hdr_strong',
	'looks_6',
	'vrpano',
	'brightness_3',
	'iso',
	'crop_7_5',
	'filter_hdr',
	'flash_auto',
	'camera_front',
	'crop_rotate',
	'wb_twilight',
	'crop_16_9',
	'tonality',
	'brightness_2',
	'camera_roll',
	'exposure',
	'filter_3',
	'photo_size_select_small',
	'filter_frames',
	'burst_mode',
	'hdr_weak',
	'linked_camera',
	'blur_linear',
	'crop_3_2',
	'photo_size_select_large',
	'crop_portrait',
	'monochrome_photos',
	'crop_5_4',
	'filter_b_and_w',
	'grid_off',
	'crop_landscape',
	'photo_camera_back',
	'24mp',
	'face_retouching_off',
	'switch_camera',
	'filter_5',
	'switch_video',
	'video_stable',
	'motion_photos_off',
	'motion_photos_paused',
	'auto_fix_off',
	'camera_rear',
	'filter_7',
	'leak_remove',
	'timer_3',
	'exposure_plus_2',
	'filter_4',
	'exposure_zero',
	'wb_shade',
	'blur_off',
	'panorama_wide_angle_select',
	'raw_on',
	'filter_6',
	'hdr_on',
	'dirty_lens',
	'filter_9',
	'panorama_photosphere',
	'30fps_select',
	'exposure_neg_2',
	'filter_9_plus',
	'vignette',
	'wb_iridescent',
	'60fps_select',
	'incomplete_circle',
	'timer_10',
	'panorama_horizontal_select',
	'exposure_neg_1',
	'motion_photos_pause',
	'panorama_horizontal',
	'filter_8',
	'image_aspect_ratio',
	'23mp',
	'panorama_photosphere_select',
	'panorama_vertical_select',
	'mic_external_off',
	'panorama_wide_angle',
	'6mp',
	'12mp',
	'hdr_plus',
	'hdr_enhanced_select',
	'autofps_select',
	'wb_auto',
	'20mp',
	'hevc',
	'13mp',
	'hdr_off',
	'mp',
	'panorama_vertical',
	'10mp',
	'11mp',
	'19mp',
	'21mp',
	'18mp',
	'22mp',
	'3mp',
	'16mp',
	'14mp',
	'15mp',
	'4mp',
	'8mp',
	'raw_off',
	'9mp',
	'17mp',
	'2mp',
	'7mp',
	'5mp',
	'local_shipping',
	'place',
	'menu_book',
	'local_offer',
	'map',
	'category',
	'directions_car',
	'restaurant',
	'badge',
	'volunteer_activism',
	'local_fire_department',
	'my_location',
	'directions_run',
	'flight',
	'handyman',
	'local_mall',
	'near_me',
	'restaurant_menu',
	'medical_services',
	'directions_walk',
	'park',
	'layers',
	'local_hospital',
	'pin_drop',
	'local_library',
	'directions_bike',
	'local_cafe',
	'celebration',
	'lunch_dining',
	'design_services',
	'local_atm',
	'directions_car_filled',
	'miscellaneous_services',
	'local_grocery_store',
	'delivery_dining',
	'person_pin',
	'rate_review',
	'local_activity',
	'local_phone',
	'home_repair_service',
	'fastfood',
	'directions_bus',
	'zoom_out_map',
	'local_police',
	'local_florist',
	'person_pin_circle',
	'hotel',
	'local_parking',
	'navigation',
	'cleaning_services',
	'local_post_office',
	'money',
	'train',
	'directions',
	'local_gas_station',
	'traffic',
	'pedal_bike',
	'alt_route',
	'electrical_services',
	'local_bar',
	'two_wheeler',
	'agriculture',
	'360',
	'directions_boat',
	'liquor',
	'beenhere',
	'local_airport',
	'moving',
	'local_dining',
	'local_drink',
	'add_business',
	'sailing',
	'ramen_dining',
	'add_location_alt',
	'hail',
	'local_taxi',
	'wine_bar',
	'local_pizza',
	'maps_ugc',
	'local_laundry_service',
	'dinner_dining',
	'theater_comedy',
	'not_listed_location',
	'add_location',
	'trip_origin',
	'bakery_dining',
	'local_printshop',
	'terrain',
	'directions_bus_filled',
	'icecream',
	'store_mall_directory',
	'transfer_within_a_station',
	'local_pharmacy',
	'multiple_stop',
	'museum',
	'nightlife',
	'set_meal',
	'car_rental',
	'takeout_dining',
	'local_see',
	'edit_road',
	'plumbing',
	'edit_location',
	'hardware',
	'ev_station',
	'pest_control',
	'emergency',
	'electric_car',
	'add_road',
	'run_circle',
	'satellite',
	'festival',
	'directions_boat_filled',
	'local_convenience_store',
	'layers_clear',
	'departure_board',
	'edit_location_alt',
	'dry_cleaning',
	'tram',
	'moped',
	'attractions',
	'breakfast_dining',
	'car_repair',
	'wrong_location',
	'edit_attributes',
	'local_movies',
	'brunch_dining',
	'directions_transit',
	'atm',
	'taxi_alert',
	'subway',
	'electric_bike',
	'electric_scooter',
	'local_car_wash',
	'hvac',
	'transit_enterexit',
	'local_hotel',
	'bus_alert',
	'streetview',
	'compass_calibration',
	'directions_subway',
	'electric_moped',
	'directions_railway',
	'electric_rickshaw',
	'no_meals',
	'railway_alert',
	'local_play',
	'bike_scooter',
	'pest_control_rodent',
	'directions_transit_filled',
	'near_me_disabled',
	'snowmobile',
	'directions_subway_filled',
	'directions_railway_filled',
	'no_transfer',
	'file_download',
	'file_upload',
	'download',
	'folder',
	'grid_view',
	'upload_file',
	'cloud',
	'cloud_upload',
	'folder_open',
	'text_snippet',
	'cloud_download',
	'request_quote',
	'attachment',
	'upload',
	'drive_file_rename_outline',
	'download_for_offline',
	'create_new_folder',
	'downloading',
	'folder_shared',
	'cloud_done',
	'topic',
	'workspaces',
	'cloud_queue',
	'cloud_off',
	'download_done',
	'approval',
	'drive_folder_upload',
	'drive_file_move',
	'file_download_done',
	'attach_email',
	'rule_folder',
	'cloud_circle',
	'snippet_folder',
	'file_download_off',
	'drive_file_move_rtl',
	'play_arrow',
	'play_circle_filled',
	'videocam',
	'play_circle',
	'volume_up',
	'mic',
	'play_circle_outline',
	'pause',
	'volume_off',
	'library_books',
	'replay',
	'stop',
	'speed',
	'skip_next',
	'movie',
	'new_releases',
	'skip_previous',
	'fiber_manual_record',
	'fast_forward',
	'playlist_add',
	'web',
	'equalizer',
	'loop',
	'volume_mute',
	'mic_off',
	'video_library',
	'pause_circle',
	'playlist_add_check',
	'library_add',
	'video_call',
	'stop_circle',
	'mic_none',
	'repeat',
	'subscriptions',
	'library_music',
	'shuffle',
	'sort_by_alpha',
	'fast_rewind',
	'videocam_off',
	'hearing',
	'not_interested',
	'pause_circle_filled',
	'album',
	'volume_down',
	'radio',
	'fiber_new',
	'subtitles',
	'recent_actors',
	'queue_music',
	'library_add_check',
	'av_timer',
	'games',
	'pause_circle_outline',
	'web_asset',
	'note',
	'forward_10',
	'branding_watermark',
	'replay_10',
	'queue',
	'playlist_play',
	'closed_caption',
	'replay_circle_filled',
	'video_settings',
	'featured_play_list',
	'closed_caption_off',
	'control_camera',
	'5g',
	'slow_motion_video',
	'add_to_queue',
	'airplay',
	'repeat_on',
	'replay_30',
	'high_quality',
	'hd',
	'shuffle_on',
	'music_video',
	'call_to_action',
	'forward_30',
	'hearing_disabled',
	'repeat_one',
	'snooze',
	'featured_video',
	'replay_5',
	'forward_5',
	'art_track',
	'4k',
	'queue_play_next',
	'video_label',
	'explicit',
	'surround_sound',
	'repeat_one_on',
	'closed_caption_disabled',
	'fiber_smart_record',
	'remove_from_queue',
	'10k',
	'web_asset_off',
	'play_disabled',
	'missed_video_call',
	'sd',
	'2k',
	'4k_plus',
	'1k',
	'8k',
	'6k_plus',
	'9k_plus',
	'5k',
	'5k_plus',
	'8k_plus',
	'fiber_dvr',
	'fiber_pin',
	'9k',
	'1k_plus',
	'3k',
	'3k_plus',
	'6k',
	'7k_plus',
	'2k_plus',
	'7k',
	'star',
	'check_box',
	'check_box_outline_blank',
	'radio_button_unchecked',
	'radio_button_checked',
	'toggle_on',
	'star_border',
	'toggle_off',
	'star_outline',
	'star_half',
	'indeterminate_check_box',
	'star_purple500',
	'star_border_purple500',
	'warning',
	'error',
	'error_outline',
	'warning_amber',
	'notification_important',
	'add_alert',
	'auto_delete',
	'attach_money',
	'format_list_bulleted',
	'mode_edit',
	'monetization_on',
	'attach_file',
	'post_add',
	'bar_chart',
	'edit_note',
	'insert_photo',
	'insert_drive_file',
	'format_quote',
	'drag_handle',
	'checklist',
	'show_chart',
	'format_list_numbered',
	'table_chart',
	'insert_emoticon',
	'border_color',
	'mode',
	'notes',
	'pie_chart',
	'auto_graph',
	'text_fields',
	'table_rows',
	'format_bold',
	'mode_edit_outline',
	'query_stats',
	'title',
	'insert_chart_outlined',
	'publish',
	'mode_comment',
	'insert_link',
	'checklist_rtl',
	'insert_invitation',
	'functions',
	'linear_scale',
	'format_size',
	'draw',
	'format_color_fill',
	'format_align_left',
	'insert_chart',
	'bubble_chart',
	'format_italic',
	'add_comment',
	'stacked_line_chart',
	'insert_comment',
	'money_off',
	'horizontal_rule',
	'vertical_align_bottom',
	'format_underlined',
	'vertical_align_top',
	'format_paint',
	'format_align_center',
	'height',
	'format_list_numbered_rtl',
	'format_color_text',
	'schema',
	'merge_type',
	'scatter_plot',
	'highlight',
	'add_chart',
	'format_align_right',
	'format_shapes',
	'format_align_justify',
	'money_off_csred',
	'format_color_reset',
	'align_horizontal_left',
	'pie_chart_outline',
	'short_text',
	'multiline_chart',
	'format_indent_increase',
	'vertical_align_center',
	'strikethrough_s',
	'border_all',
	'score',
	'area_chart',
	'format_line_spacing',
	'horizontal_distribute',
	'space_bar',
	'format_strikethrough',
	'vertical_distribute',
	'format_indent_decrease',
	'align_vertical_bottom',
	'format_clear',
	'align_horizontal_center',
	'align_horizontal_right',
	'margin',
	'superscript',
	'align_vertical_center',
	'align_vertical_top',
	'subscript',
	'border_clear',
	'wrap_text',
	'border_outer',
	'padding',
	'border_style',
	'border_bottom',
	'format_textdirection_l_to_r',
	'border_inner',
	'border_vertical',
	'format_textdirection_r_to_l',
	'border_top',
	'border_horizontal',
	'border_left',
	'border_right',
	'support_agent',
	'wifi',
	'account_tree',
	'event_available',
	'phone_in_talk',
	'priority_high',
	'sync',
	'event_note',
	'sms',
	'live_tv',
	'confirmation_number',
	'ondemand_video',
	'wc',
	'do_not_disturb_on',
	'wifi_off',
	'drive_eta',
	'more',
	'do_not_disturb',
	'event_busy',
	'power',
	'do_disturb_on',
	'time_to_leave',
	'vpn_lock',
	'enhanced_encryption',
	'folder_special',
	'sync_problem',
	'running_with_errors',
	'network_check',
	'do_disturb',
	'system_update',
	'adb',
	'voice_chat',
	'phone_callback',
	'power_off',
	'sms_failed',
	'phone_forwarded',
	'personal_video',
	'vibration',
	'airline_seat_recline_normal',
	'do_disturb_alt',
	'do_not_disturb_alt',
	'no_encryption',
	'sync_disabled',
	'sd_card',
	'phone_missed',
	'tap_and_play',
	'airline_seat_recline_extra',
	'imagesearch_roller',
	'mms',
	'bluetooth_audio',
	'disc_full',
	'no_encryption_gmailerrorred',
	'phone_paused',
	'airline_seat_individual_suite',
	'do_not_disturb_off',
	'network_locked',
	'do_disturb_off',
	'phone_locked',
	'sd_card_alert',
	'sim_card_alert',
	'airline_seat_flat_angled',
	'tv_off',
	'phone_bluetooth_speaker',
	'directions_off',
	'airline_seat_flat',
	'airline_seat_legroom_extra',
	'airline_seat_legroom_normal',
	'airline_seat_legroom_reduced',
	'keyboard_arrow_down',
	'phone_iphone',
	'smartphone',
	'keyboard_arrow_right',
	'computer',
	'security',
	'desktop_windows',
	'phone_android',
	'smart_display',
	'tv',
	'smart_toy',
	'keyboard_arrow_up',
	'keyboard_backspace',
	'keyboard_arrow_left',
	'headphones',
	'headset_mic',
	'laptop',
	'keyboard',
	'memory',
	'point_of_sale',
	'keyboard_return',
	'mouse',
	'keyboard_voice',
	'developer_board',
	'videogame_asset',
	'device_hub',
	'laptop_chromebook',
	'headset',
	'cast_for_education',
	'router',
	'laptop_mac',
	'watch',
	'cast',
	'monitor',
	'devices_other',
	'tablet_mac',
	'speaker',
	'desktop_mac',
	'phonelink',
	'keyboard_tab',
	'connected_tv',
	'toys',
	'gamepad',
	'keyboard_alt',
	'tablet_android',
	'cast_connected',
	'sim_card',
	'device_unknown',
	'laptop_windows',
	'headset_off',
	'scanner',
	'tablet',
	'keyboard_hide',
	'speaker_group',
	'earbuds',
	'keyboard_capslock',
	'home_max',
	'home_mini',
	'headphones_battery',
	'earbuds_battery',
	'smart_screen',
	'power_input',
	'browser_not_supported',
	'dock',
	'developer_board_off',
	'phonelink_off',
	'videogame_asset_off',
	'light_mode',
	'dark_mode',
	'restart_alt',
	'task',
	'password',
	'devices',
	'summarize',
	'sell',
	'settings_suggest',
	'quiz',
	'signal_cellular_alt',
	'thermostat',
	'widgets',
	'storage',
	'credit_score',
	'battery_full',
	'price_check',
	'gps_fixed',
	'medication',
	'pin',
	'battery_charging_full',
	'tungsten',
	'gpp_good',
	'price_change',
	'reviews',
	'air',
	'note_alt',
	'graphic_eq',
	'access_time',
	'bluetooth',
	'fmd_good',
	'water',
	'dvr',
	'sports_score',
	'nightlight',
	'share_location',
	'gpp_maybe',
	'monitor_weight',
	'bloodtype',
	'wifi_tethering',
	'airplane_ticket',
	'device_thermostat',
	'cameraswitch',
	'battery_std',
	'cable',
	'location_searching',
	'mode_night',
	'radar',
	'signal_wifi_4_bar',
	'data_usage',
	'shortcut',
	'lens_blur',
	'signal_cellular_4_bar',
	'wallpaper',
	'gpp_bad',
	'network_wifi',
	'developer_mode',
	'fmd_bad',
	'access_time_filled',
	'airplanemode_active',
	'screen_search_desktop',
	'signal_wifi_statusbar_4_bar',
	'splitscreen',
	'usb',
	'flashlight_on',
	'bluetooth_connected',
	'battery_alert',
	'sim_card_download',
	'mobile_friendly',
	'send_to_mobile',
	'nfc',
	'system_security_update_good',
	'storm',
	'remember_me',
	'gps_not_fixed',
	'screenshot',
	'signal_wifi_statusbar_connected_no_internet_4',
	'battery_saver',
	'mode_standby',
	'screen_rotation',
	'pattern',
	'data_saver_off',
	'play_lesson',
	'brightness_high',
	'network_cell',
	'signal_wifi_0_bar',
	'grid_4x4',
	'brightness_low',
	'aod',
	'bluetooth_searching',
	'ad_units',
	'data_saver_on',
	'mobiledata_off',
	'access_alarms',
	'bluetooth_disabled',
	'security_update_good',
	'signal_wifi_bad',
	'brightness_medium',
	'hdr_auto',
	'security_update',
	'signal_wifi_off',
	'wifi_lock',
	'settings_system_daydream',
	'4g_mobiledata',
	'battery_unknown',
	'wifi_calling_3',
	'flourescent',
	'sd_storage',
	'signal_cellular_0_bar',
	'gps_off',
	'add_to_home_screen',
	'do_not_disturb_on_total_silence',
	'signal_wifi_connected_no_internet_4',
	'access_alarm',
	'grid_3x3',
	'signal_wifi_statusbar_null',
	'brightness_auto',
	'wifi_tethering_error_rounded',
	'1x_mobiledata',
	'nearby_error',
	'screen_lock_portrait',
	'30fps',
	'60fps',
	'reset_tv',
	'signal_wifi_4_bar_lock',
	'flashlight_off',
	'lte_mobiledata',
	'airplanemode_inactive',
	'edgesensor_high',
	'signal_cellular_connected_no_internet_4_bar',
	'media_bluetooth_on',
	'security_update_warning',
	'4g_plus_mobiledata',
	'bluetooth_drive',
	'location_disabled',
	'signal_cellular_off',
	'system_security_update',
	'wifi_tethering_off',
	'timer_10_select',
	'3g_mobiledata',
	'add_alarm',
	'signal_cellular_connected_no_internet_0_bar',
	'system_security_update_warning',
	'signal_cellular_null',
	'timer_3_select',
	'edgesensor_low',
	'rsvp',
	'signal_cellular_nodata',
	'mobile_off',
	'screen_lock_rotation',
	'lte_plus_mobiledata',
	'usb_off',
	'grid_goldenratio',
	'screen_lock_landscape',
	'signal_cellular_no_sim',
	'g_mobiledata',
	'r_mobiledata',
	'h_mobiledata',
	'e_mobiledata',
	'media_bluetooth_off',
	'hdr_auto_select',
	'hdr_on_select',
	'hdr_off_select',
	'nearby_off',
	'h_plus_mobiledata',
	'storefront',
	'apartment',
	'fitness_center',
	'house',
	'spa',
	'business_center',
	'cottage',
	'meeting_room',
	'corporate_fare',
	'ac_unit',
	'family_restroom',
	'all_inclusive',
	'checkroom',
	'grass',
	'airport_shuttle',
	'other_houses',
	'pool',
	'child_care',
	'beach_access',
	'kitchen',
	'holiday_village',
	'casino',
	'roofing',
	'free_breakfast',
	'sports_bar',
	'room_service',
	'gite',
	'foundation',
	'escalator_warning',
	'room_preferences',
	'child_friendly',
	'food_bank',
	'villa',
	'bathtub',
	'night_shelter',
	'golf_course',
	'wash',
	'stairs',
	'backpack',
	'smoking_rooms',
	'microwave',
	'hot_tub',
	'water_damage',
	'fire_extinguisher',
	'house_siding',
	'cabin',
	'countertops',
	'baby_changing_station',
	'soap',
	'elevator',
	'no_photography',
	'wheelchair_pickup',
	'rv_hookup',
	'carpenter',
	'smoke_free',
	'tapas',
	'charging_station',
	'umbrella',
	'rice_bowl',
	'no_food',
	'fence',
	'balcony',
	'houseboat',
	'iron',
	'bento',
	'bungalow',
	'do_not_touch',
	'crib',
	'escalator',
	'dry',
	'chalet',
	'stroller',
	'tty',
	'do_not_step',
	'no_meeting_room',
	'no_drinks',
	'no_flash',
	'no_cell',
	'no_backpack',
	'no_stroller',
	'feed',
	'manage_search',
	'bed',
	'chair',
	'podcasts',
	'coffee',
	'shower',
	'yard',
	'light',
	'window',
	'door_front',
	'garage',
	'dining',
	'blender',
	'bedroom_baby',
	'flatware',
	'camera_indoor',
	'coffee_maker',
	'bathroom',
	'bedroom_parent',
	'camera_outdoor',
	'door_sliding',
	'chair_alt',
	'living',
	'bedroom_child',
	'door_back',
	'doorbell',
	'sensor_door',
	'sensor_window',
];

const allDash = [
	'dashicons-admin-appearance',
	'dashicons-admin-collapse',
	'dashicons-admin-comments',
	'dashicons-admin-customizer',
	'dashicons-admin-generic',
	'dashicons-admin-home',
	'dashicons-admin-links',
	'dashicons-admin-media',
	'dashicons-admin-multisite',
	'dashicons-admin-network',
	'dashicons-admin-page',
	'dashicons-admin-plugins',
	'dashicons-admin-post',
	'dashicons-admin-settings',
	'dashicons-admin-site-alt',
	'dashicons-admin-site-alt2',
	'dashicons-admin-site-alt3',
	'dashicons-admin-site',
	'dashicons-admin-tools',
	'dashicons-admin-users',
	'dashicons-album',
	'dashicons-align-center',
	'dashicons-align-left',
	'dashicons-align-none',
	'dashicons-align-right',
	'dashicons-analytics',
	'dashicons-archive',
	'dashicons-arrow-down-alt',
	'dashicons-arrow-down-alt2',
	'dashicons-arrow-down',
	'dashicons-arrow-left-alt',
	'dashicons-arrow-left-alt2',
	'dashicons-arrow-left',
	'dashicons-arrow-right-alt',
	'dashicons-arrow-right-alt2',
	'dashicons-arrow-right',
	'dashicons-arrow-up-alt',
	'dashicons-arrow-up-alt2',
	'dashicons-arrow-up',
	'dashicons-art',
	'dashicons-awards',
	'dashicons-backup',
	'dashicons-book-alt',
	'dashicons-book',
	'dashicons-buddicons-activity',
	'dashicons-buddicons-bbpress-logo',
	'dashicons-buddicons-buddypress-logo',
	'dashicons-buddicons-community',
	'dashicons-buddicons-forums',
	'dashicons-buddicons-friends',
	'dashicons-buddicons-groups',
	'dashicons-buddicons-pm',
	'dashicons-buddicons-replies',
	'dashicons-buddicons-topics',
	'dashicons-buddicons-tracking',
	'dashicons-building',
	'dashicons-businessman',
	'dashicons-calendar-alt',
	'dashicons-calendar',
	'dashicons-camera',
	'dashicons-carrot',
	'dashicons-cart',
	'dashicons-category',
	'dashicons-chart-area',
	'dashicons-chart-bar',
	'dashicons-chart-line',
	'dashicons-chart-pie',
	'dashicons-clipboard',
	'dashicons-clock',
	'dashicons-cloud',
	'dashicons-controls-back',
	'dashicons-controls-forward',
	'dashicons-controls-pause',
	'dashicons-controls-play',
	'dashicons-controls-repeat',
	'dashicons-controls-skipback',
	'dashicons-controls-skipforward',
	'dashicons-controls-volumeoff',
	'dashicons-controls-volumeon',
	'dashicons-dashboard',
	'dashicons-desktop',
	'dashicons-dismiss',
	'dashicons-download',
	'dashicons-edit',
	'dashicons-editor-aligncenter',
	'dashicons-editor-alignleft',
	'dashicons-editor-alignright',
	'dashicons-editor-bold',
	'dashicons-editor-break',
	'dashicons-editor-code',
	'dashicons-editor-contract',
	'dashicons-editor-customchar',
	'dashicons-editor-expand',
	'dashicons-editor-help',
	'dashicons-editor-indent',
	'dashicons-editor-insertmore',
	'dashicons-editor-italic',
	'dashicons-editor-justify',
	'dashicons-editor-kitchensink',
	'dashicons-editor-ltr',
	'dashicons-editor-ol',
	'dashicons-editor-outdent',
	'dashicons-editor-paragraph',
	'dashicons-editor-paste-text',
	'dashicons-editor-paste-word',
	'dashicons-editor-quote',
	'dashicons-editor-removeformatting',
	'dashicons-editor-rtl',
	'dashicons-editor-spellcheck',
	'dashicons-editor-strikethrough',
	'dashicons-editor-table',
	'dashicons-editor-textcolor',
	'dashicons-editor-ul',
	'dashicons-editor-underline',
	'dashicons-editor-unlink',
	'dashicons-editor-video',
	'dashicons-email-alt',
	'dashicons-email-alt2',
	'dashicons-email',
	'dashicons-excerpt-view',
	'dashicons-external',
	'dashicons-facebook-alt',
	'dashicons-facebook',
	'dashicons-feedback',
	'dashicons-filter',
	'dashicons-flag',
	'dashicons-format-aside',
	'dashicons-format-audio',
	'dashicons-format-chat',
	'dashicons-format-gallery',
	'dashicons-format-image',
	'dashicons-format-quote',
	'dashicons-format-status',
	'dashicons-format-video',
	'dashicons-forms',
	'dashicons-googleplus',
	'dashicons-grid-view',
	'dashicons-groups',
	'dashicons-hammer',
	'dashicons-heart',
	'dashicons-hidden',
	'dashicons-id-alt',
	'dashicons-id',
	'dashicons-image-crop',
	'dashicons-image-filter',
	'dashicons-image-flip-horizontal',
	'dashicons-image-flip-vertical',
	'dashicons-image-rotate-left',
	'dashicons-image-rotate-right',
	'dashicons-image-rotate',
	'dashicons-images-alt',
	'dashicons-images-alt2',
	'dashicons-index-card',
	'dashicons-info',
	'dashicons-laptop',
	'dashicons-layout',
	'dashicons-leftright',
	'dashicons-lightbulb',
	'dashicons-list-view',
	'dashicons-location-alt',
	'dashicons-location',
	'dashicons-lock',
	'dashicons-marker',
	'dashicons-media-archive',
	'dashicons-media-audio',
	'dashicons-media-code',
	'dashicons-media-default',
	'dashicons-media-document',
	'dashicons-media-interactive',
	'dashicons-media-spreadsheet',
	'dashicons-media-text',
	'dashicons-media-video',
	'dashicons-megaphone',
	'dashicons-menu-alt',
	'dashicons-menu',
	'dashicons-microphone',
	'dashicons-migrate',
	'dashicons-minus',
	'dashicons-money',
	'dashicons-move',
	'dashicons-nametag',
	'dashicons-networking',
	'dashicons-no-alt',
	'dashicons-no',
	'dashicons-palmtree',
	'dashicons-paperclip',
	'dashicons-performance',
	'dashicons-phone',
	'dashicons-playlist-audio',
	'dashicons-playlist-video',
	'dashicons-plus-alt',
	'dashicons-plus',
	'dashicons-portfolio',
	'dashicons-post-status',
	'dashicons-pressthis',
	'dashicons-products',
	'dashicons-randomize',
	'dashicons-redo',
	'dashicons-rest-api',
	'dashicons-rss',
	'dashicons-schedule',
	'dashicons-screenoptions',
	'dashicons-search',
	'dashicons-share-alt',
	'dashicons-share-alt2',
	'dashicons-share',
	'dashicons-shield-alt',
	'dashicons-shield',
	'dashicons-slides',
	'dashicons-smartphone',
	'dashicons-smiley',
	'dashicons-sort',
	'dashicons-sos',
	'dashicons-star-empty',
	'dashicons-star-filled',
	'dashicons-star-half',
	'dashicons-sticky',
	'dashicons-store',
	'dashicons-tablet',
	'dashicons-tag',
	'dashicons-tagcloud',
	'dashicons-testimonial',
	'dashicons-text',
	'dashicons-thumbs-down',
	'dashicons-thumbs-up',
	'dashicons-tickets-alt',
	'dashicons-tickets',
	'dashicons-tide',
	'dashicons-translation',
	'dashicons-trash',
	'dashicons-twitter',
	'dashicons-undo',
	'dashicons-universal-access-alt',
	'dashicons-universal-access',
	'dashicons-unlock',
	'dashicons-update',
	'dashicons-upload',
	'dashicons-vault',
	'dashicons-video-alt',
	'dashicons-video-alt2',
	'dashicons-video-alt3',
	'dashicons-visibility',
	'dashicons-warning',
	'dashicons-welcome-add-page',
	'dashicons-welcome-comments',
	'dashicons-welcome-learn-more',
	'dashicons-welcome-view-site',
	'dashicons-welcome-widgets-menus',
	'dashicons-welcome-write-blog',
	'dashicons-wordpress-alt',
	'dashicons-wordpress',
	'dashicons-yes-alt',
	'dashicons-yes',
];
