const FASOLIDicons = [
	'ad',
	'address-book',
	'address-card',
	'adjust',
	'air-freshener',
	'align-center',
	'align-justify',
	'align-left',
	'align-right',
	'allergies',
	'ambulance',
	'american-sign-language-interpreting',
	'anchor',
	'angle-double-down',
	'angle-double-left',
	'angle-double-right',
	'angle-double-up',
	'angle-down',
	'angle-left',
	'angle-right',
	'angle-up',
	'angry',
	'ankh',
	'apple-alt',
	'archive',
	'archway',
	'arrow-alt-circle-down',
	'arrow-alt-circle-left',
	'arrow-alt-circle-right',
	'arrow-alt-circle-up',
	'arrow-circle-down',
	'arrow-circle-left',
	'arrow-circle-right',
	'arrow-circle-up',
	'arrow-down',
	'arrow-left',
	'arrow-right',
	'arrow-up',
	'arrows-alt',
	'arrows-alt-h',
	'arrows-alt-v',
	'assistive-listening-systems',
	'asterisk',
	'at',
	'atlas',
	'atom',
	'audio-description',
	'award',
	'baby',
	'baby-carriage',
	'backspace',
	'backward',
	'bacon',
	'bahai',
	'balance-scale',
	'balance-scale-left',
	'balance-scale-right',
	'ban',
	'band-aid',
	'barcode',
	'bars',
	'baseball-ball',
	'basketball-ball',
	'bath',
	'battery-empty',
	'battery-full',
	'battery-half',
	'battery-quarter',
	'battery-three-quarters',
	'bed',
	'beer',
	'bell',
	'bell-slash',
	'bezier-curve',
	'bible',
	'bicycle',
	'biking',
	'binoculars',
	'biohazard',
	'birthday-cake',
	'blender',
	'blender-phone',
	'blind',
	'blog',
	'bold',
	'bolt',
	'bomb',
	'bone',
	'bong',
	'book',
	'book-dead',
	'book-medical',
	'book-open',
	'book-reader',
	'bookmark',
	'border-all',
	'border-none',
	'border-style',
	'bowling-ball',
	'box',
	'box-open',
	'boxes',
	'braille',
	'brain',
	'bread-slice',
	'briefcase',
	'briefcase-medical',
	'broadcast-tower',
	'broom',
	'brush',
	'bug',
	'building',
	'bullhorn',
	'bullseye',
	'burn',
	'bus',
	'bus-alt',
	'business-time',
	'calculator',
	'calendar',
	'calendar-alt',
	'calendar-check',
	'calendar-day',
	'calendar-minus',
	'calendar-plus',
	'calendar-times',
	'calendar-week',
	'camera',
	'camera-retro',
	'campground',
	'candy-cane',
	'cannabis',
	'capsules',
	'car',
	'car-alt',
	'car-battery',
	'car-crash',
	'car-side',
	'caravan',
	'caret-down',
	'caret-left',
	'caret-right',
	'caret-square-down',
	'caret-square-left',
	'caret-square-right',
	'caret-square-up',
	'caret-up',
	'carrot',
	'cart-arrow-down',
	'cart-plus',
	'cash-register',
	'cat',
	'certificate',
	'chair',
	'chalkboard',
	'chalkboard-teacher',
	'charging-station',
	'chart-area',
	'chart-bar',
	'chart-line',
	'chart-pie',
	'check',
	'check-circle',
	'check-double',
	'check-square',
	'cheese',
	'chess',
	'chess-bishop',
	'chess-board',
	'chess-king',
	'chess-knight',
	'chess-pawn',
	'chess-queen',
	'chess-rook',
	'chevron-circle-down',
	'chevron-circle-left',
	'chevron-circle-right',
	'chevron-circle-up',
	'chevron-down',
	'chevron-left',
	'chevron-right',
	'chevron-up',
	'child',
	'church',
	'circle',
	'circle-notch',
	'city',
	'clinic-medical',
	'clipboard',
	'clipboard-check',
	'clipboard-list',
	'clock',
	'clone',
	'closed-captioning',
	'cloud',
	'cloud-download-alt',
	'cloud-meatball',
	'cloud-moon',
	'cloud-moon-rain',
	'cloud-rain',
	'cloud-showers-heavy',
	'cloud-sun',
	'cloud-sun-rain',
	'cloud-upload-alt',
	'cocktail',
	'code',
	'code-branch',
	'coffee',
	'cog',
	'cogs',
	'coins',
	'columns',
	'comment',
	'comment-alt',
	'comment-dollar',
	'comment-dots',
	'comment-medical',
	'comment-slash',
	'comments',
	'comments-dollar',
	'compact-disc',
	'compass',
	'compress',
	'compress-alt',
	'compress-arrows-alt',
	'concierge-bell',
	'cookie',
	'cookie-bite',
	'copy',
	'copyright',
	'couch',
	'credit-card',
	'crop',
	'crop-alt',
	'cross',
	'crosshairs',
	'crow',
	'crown',
	'crutch',
	'cube',
	'cubes',
	'cut',
	'database',
	'deaf',
	'democrat',
	'desktop',
	'dharmachakra',
	'diagnoses',
	'dice',
	'dice-d20',
	'dice-d6',
	'dice-five',
	'dice-four',
	'dice-one',
	'dice-six',
	'dice-three',
	'dice-two',
	'digital-tachograph',
	'directions',
	'divide',
	'dizzy',
	'dna',
	'dog',
	'dollar-sign',
	'dolly',
	'dolly-flatbed',
	'donate',
	'door-closed',
	'door-open',
	'dot-circle',
	'dove',
	'download',
	'drafting-compass',
	'dragon',
	'draw-polygon',
	'drum',
	'drum-steelpan',
	'drumstick-bite',
	'dumbbell',
	'dumpster',
	'dumpster-fire',
	'dungeon',
	'edit',
	'egg',
	'eject',
	'ellipsis-h',
	'ellipsis-v',
	'envelope',
	'envelope-open',
	'envelope-open-text',
	'envelope-square',
	'equals',
	'eraser',
	'ethernet',
	'euro-sign',
	'exchange-alt',
	'exclamation',
	'exclamation-circle',
	'exclamation-triangle',
	'expand',
	'expand-alt',
	'expand-arrows-alt',
	'external-link-alt',
	'external-link-square-alt',
	'eye',
	'eye-dropper',
	'eye-slash',
	'fan',
	'fast-backward',
	'fast-forward',
	'fax',
	'feather',
	'feather-alt',
	'female',
	'fighter-jet',
	'file',
	'file-alt',
	'file-archive',
	'file-audio',
	'file-code',
	'file-contract',
	'file-csv',
	'file-download',
	'file-excel',
	'file-export',
	'file-image',
	'file-import',
	'file-invoice',
	'file-invoice-dollar',
	'file-medical',
	'file-medical-alt',
	'file-pdf',
	'file-powerpoint',
	'file-prescription',
	'file-signature',
	'file-upload',
	'file-video',
	'file-word',
	'fill',
	'fill-drip',
	'film',
	'filter',
	'fingerprint',
	'fire',
	'fire-alt',
	'fire-extinguisher',
	'first-aid',
	'fish',
	'fist-raised',
	'flag',
	'flag-checkered',
	'flag-usa',
	'flask',
	'flushed',
	'folder',
	'folder-minus',
	'folder-open',
	'folder-plus',
	'font',
	'football-ball',
	'forward',
	'frog',
	'frown',
	'frown-open',
	'funnel-dollar',
	'futbol',
	'gamepad',
	'gas-pump',
	'gavel',
	'gem',
	'genderless',
	'ghost',
	'gift',
	'gifts',
	'glass-cheers',
	'glass-martini',
	'glass-martini-alt',
	'glass-whiskey',
	'glasses',
	'globe',
	'globe-africa',
	'globe-americas',
	'globe-asia',
	'globe-europe',
	'golf-ball',
	'gopuram',
	'graduation-cap',
	'greater-than',
	'greater-than-equal',
	'grimace',
	'grin',
	'grin-alt',
	'grin-beam',
	'grin-beam-sweat',
	'grin-hearts',
	'grin-squint',
	'grin-squint-tears',
	'grin-stars',
	'grin-tears',
	'grin-tongue',
	'grin-tongue-squint',
	'grin-tongue-wink',
	'grin-wink',
	'grip-horizontal',
	'grip-lines',
	'grip-lines-vertical',
	'grip-vertical',
	'guitar',
	'h-square',
	'hamburger',
	'hammer',
	'hamsa',
	'hand-holding',
	'hand-holding-heart',
	'hand-holding-usd',
	'hand-lizard',
	'hand-middle-finger',
	'hand-paper',
	'hand-peace',
	'hand-point-down',
	'hand-point-left',
	'hand-point-right',
	'hand-point-up',
	'hand-pointer',
	'hand-rock',
	'hand-scissors',
	'hand-spock',
	'hands',
	'hands-helping',
	'handshake',
	'hanukiah',
	'hard-hat',
	'hashtag',
	'hat-cowboy',
	'hat-cowboy-side',
	'hat-wizard',
	'hdd',
	'heading',
	'headphones',
	'headphones-alt',
	'headset',
	'heart',
	'heart-broken',
	'heartbeat',
	'helicopter',
	'highlighter',
	'hiking',
	'hippo',
	'history',
	'hockey-puck',
	'holly-berry',
	'home',
	'horse',
	'horse-head',
	'hospital',
	'hospital-alt',
	'hospital-symbol',
	'hot-tub',
	'hotdog',
	'hotel',
	'hourglass',
	'hourglass-end',
	'hourglass-half',
	'hourglass-start',
	'house-damage',
	'hryvnia',
	'i-cursor',
	'ice-cream',
	'icicles',
	'icons',
	'id-badge',
	'id-card',
	'id-card-alt',
	'igloo',
	'image',
	'images',
	'inbox',
	'indent',
	'industry',
	'infinity',
	'info',
	'info-circle',
	'italic',
	'jedi',
	'joint',
	'journal-whills',
	'kaaba',
	'key',
	'keyboard',
	'khanda',
	'kiss',
	'kiss-beam',
	'kiss-wink-heart',
	'kiwi-bird',
	'landmark',
	'language',
	'laptop',
	'laptop-code',
	'laptop-medical',
	'laugh',
	'laugh-beam',
	'laugh-squint',
	'laugh-wink',
	'layer-group',
	'leaf',
	'lemon',
	'less-than',
	'less-than-equal',
	'level-down-alt',
	'level-up-alt',
	'life-ring',
	'lightbulb',
	'link',
	'lira-sign',
	'list',
	'list-alt',
	'list-ol',
	'list-ul',
	'location-arrow',
	'lock',
	'lock-open',
	'long-arrow-alt-down',
	'long-arrow-alt-left',
	'long-arrow-alt-right',
	'long-arrow-alt-up',
	'low-vision',
	'luggage-cart',
	'magic',
	'magnet',
	'mail-bulk',
	'male',
	'map',
	'map-marked',
	'map-marked-alt',
	'map-marker',
	'map-marker-alt',
	'map-pin',
	'map-signs',
	'marker',
	'mars',
	'mars-double',
	'mars-stroke',
	'mars-stroke-h',
	'mars-stroke-v',
	'mask',
	'medal',
	'medkit',
	'meh',
	'meh-blank',
	'meh-rolling-eyes',
	'memory',
	'menorah',
	'mercury',
	'meteor',
	'microchip',
	'microphone',
	'microphone-alt',
	'microphone-alt-slash',
	'microphone-slash',
	'microscope',
	'minus',
	'minus-circle',
	'minus-square',
	'mitten',
	'mobile',
	'mobile-alt',
	'money-bill',
	'money-bill-alt',
	'money-bill-wave',
	'money-bill-wave-alt',
	'money-check',
	'money-check-alt',
	'monument',
	'moon',
	'mortar-pestle',
	'mosque',
	'motorcycle',
	'mountain',
	'mouse',
	'mouse-pointer',
	'mug-hot',
	'music',
	'network-wired',
	'neuter',
	'newspaper',
	'not-equal',
	'notes-medical',
	'object-group',
	'object-ungroup',
	'oil-can',
	'om',
	'otter',
	'outdent',
	'pager',
	'paint-brush',
	'paint-roller',
	'palette',
	'pallet',
	'paper-plane',
	'paperclip',
	'parachute-box',
	'paragraph',
	'parking',
	'passport',
	'pastafarianism',
	'paste',
	'pause',
	'pause-circle',
	'paw',
	'peace',
	'pen',
	'pen-alt',
	'pen-fancy',
	'pen-nib',
	'pen-square',
	'pencil-alt',
	'pencil-ruler',
	'people-carry',
	'pepper-hot',
	'percent',
	'percentage',
	'person-booth',
	'phone',
	'phone-alt',
	'phone-slash',
	'phone-square',
	'phone-square-alt',
	'phone-volume',
	'photo-video',
	'piggy-bank',
	'pills',
	'pizza-slice',
	'place-of-worship',
	'plane',
	'plane-arrival',
	'plane-departure',
	'play',
	'play-circle',
	'plug',
	'plus',
	'plus-circle',
	'plus-square',
	'podcast',
	'poll',
	'poll-h',
	'poo',
	'poo-storm',
	'poop',
	'portrait',
	'pound-sign',
	'power-off',
	'pray',
	'praying-hands',
	'prescription',
	'prescription-bottle',
	'prescription-bottle-alt',
	'print',
	'procedures',
	'project-diagram',
	'puzzle-piece',
	'qrcode',
	'question',
	'question-circle',
	'quidditch',
	'quote-left',
	'quote-right',
	'quran',
	'radiation',
	'radiation-alt',
	'rainbow',
	'random',
	'receipt',
	'record-vinyl',
	'recycle',
	'redo',
	'redo-alt',
	'registered',
	'remove-format',
	'reply',
	'reply-all',
	'republican',
	'restroom',
	'retweet',
	'ribbon',
	'ring',
	'road',
	'robot',
	'rocket',
	'route',
	'rss',
	'rss-square',
	'ruble-sign',
	'ruler',
	'ruler-combined',
	'ruler-horizontal',
	'ruler-vertical',
	'running',
	'rupee-sign',
	'sad-cry',
	'sad-tear',
	'satellite',
	'satellite-dish',
	'save',
	'school',
	'screwdriver',
	'scroll',
	'sd-card',
	'search',
	'search-dollar',
	'search-location',
	'search-minus',
	'search-plus',
	'seedling',
	'server',
	'shapes',
	'share',
	'share-alt',
	'share-alt-square',
	'share-square',
	'shekel-sign',
	'shield-alt',
	'ship',
	'shipping-fast',
	'shoe-prints',
	'shopping-bag',
	'shopping-basket',
	'shopping-cart',
	'shower',
	'shuttle-van',
	'sign',
	'sign-in-alt',
	'sign-language',
	'sign-out-alt',
	'signal',
	'signature',
	'sim-card',
	'sitemap',
	'skating',
	'skiing',
	'skiing-nordic',
	'skull',
	'skull-crossbones',
	'slash',
	'sleigh',
	'sliders-h',
	'smile',
	'smile-beam',
	'smile-wink',
	'smog',
	'smoking',
	'smoking-ban',
	'sms',
	'snowboarding',
	'snowflake',
	'snowman',
	'snowplow',
	'socks',
	'solar-panel',
	'sort',
	'sort-alpha-down',
	'sort-alpha-down-alt',
	'sort-alpha-up',
	'sort-alpha-up-alt',
	'sort-amount-down',
	'sort-amount-down-alt',
	'sort-amount-up',
	'sort-amount-up-alt',
	'sort-down',
	'sort-numeric-down',
	'sort-numeric-down-alt',
	'sort-numeric-up',
	'sort-numeric-up-alt',
	'sort-up',
	'spa',
	'space-shuttle',
	'spell-check',
	'spider',
	'spinner',
	'splotch',
	'spray-can',
	'square',
	'square-full',
	'square-root-alt',
	'stamp',
	'star',
	'star-and-crescent',
	'star-half',
	'star-half-alt',
	'star-of-david',
	'star-of-life',
	'step-backward',
	'step-forward',
	'stethoscope',
	'sticky-note',
	'stop',
	'stop-circle',
	'stopwatch',
	'store',
	'store-alt',
	'stream',
	'street-view',
	'strikethrough',
	'stroopwafel',
	'subscript',
	'subway',
	'suitcase',
	'suitcase-rolling',
	'sun',
	'superscript',
	'surprise',
	'swatchbook',
	'swimmer',
	'swimming-pool',
	'synagogue',
	'sync',
	'sync-alt',
	'syringe',
	'table',
	'table-tennis',
	'tablet',
	'tablet-alt',
	'tablets',
	'tachometer-alt',
	'tag',
	'tags',
	'tape',
	'tasks',
	'taxi',
	'teeth',
	'teeth-open',
	'temperature-high',
	'temperature-low',
	'tenge',
	'terminal',
	'text-height',
	'text-width',
	'th',
	'th-large',
	'th-list',
	'theater-masks',
	'thermometer',
	'thermometer-empty',
	'thermometer-full',
	'thermometer-half',
	'thermometer-quarter',
	'thermometer-three-quarters',
	'thumbs-down',
	'thumbs-up',
	'thumbtack',
	'ticket-alt',
	'times',
	'times-circle',
	'tint',
	'tint-slash',
	'tired',
	'toggle-off',
	'toggle-on',
	'toilet',
	'toilet-paper',
	'toolbox',
	'tools',
	'tooth',
	'torah',
	'torii-gate',
	'tractor',
	'trademark',
	'traffic-light',
	'trailer',
	'train',
	'tram',
	'transgender',
	'transgender-alt',
	'trash',
	'trash-alt',
	'trash-restore',
	'trash-restore-alt',
	'tree',
	'trophy',
	'truck',
	'truck-loading',
	'truck-monster',
	'truck-moving',
	'truck-pickup',
	'tshirt',
	'tty',
	'tv',
	'umbrella',
	'umbrella-beach',
	'underline',
	'undo',
	'undo-alt',
	'universal-access',
	'university',
	'unlink',
	'unlock',
	'unlock-alt',
	'upload',
	'user',
	'user-alt',
	'user-alt-slash',
	'user-astronaut',
	'user-check',
	'user-circle',
	'user-clock',
	'user-cog',
	'user-edit',
	'user-friends',
	'user-graduate',
	'user-injured',
	'user-lock',
	'user-md',
	'user-minus',
	'user-ninja',
	'user-nurse',
	'user-plus',
	'user-secret',
	'user-shield',
	'user-slash',
	'user-tag',
	'user-tie',
	'user-times',
	'users',
	'users-cog',
	'utensil-spoon',
	'utensils',
	'vector-square',
	'venus',
	'venus-double',
	'venus-mars',
	'vial',
	'vials',
	'video',
	'video-slash',
	'vihara',
	'voicemail',
	'volleyball-ball',
	'volume-down',
	'volume-mute',
	'volume-off',
	'volume-up',
	'vote-yea',
	'vr-cardboard',
	'walking',
	'wallet',
	'warehouse',
	'water',
	'wave-square',
	'weight',
	'weight-hanging',
	'wheelchair',
	'wifi',
	'wind',
	'window-close',
	'window-maximize',
	'window-minimize',
	'window-restore',
	'wine-bottle',
	'wine-glass',
	'wine-glass-alt',
	'won-sign',
	'wrench',
	'x-ray',
	'yen-sign',
	'yin-yang',
];

const FAREG = [
	'address-book',
	'address-card',
	'angry',
	'arrow-alt-circle-down',
	'arrow-alt-circle-left',
	'arrow-alt-circle-right',
	'arrow-alt-circle-up',
	'bell',
	'bell-slash',
	'bookmark',
	'building',
	'calendar',
	'calendar-alt',
	'calendar-check',
	'calendar-minus',
	'calendar-plus',
	'calendar-times',
	'caret-square-down',
	'caret-square-left',
	'caret-square-right',
	'caret-square-up',
	'chart-bar',
	'check-circle',
	'check-square',
	'circle',
	'clipboard',
	'clock',
	'clone',
	'closed-captioning',
	'comment',
	'comment-alt',
	'comment-dots',
	'comments',
	'compass',
	'copy',
	'copyright',
	'credit-card',
	'dizzy',
	'dot-circle',
	'edit',
	'envelope',
	'envelope-open',
	'eye',
	'eye-slash',
	'file',
	'file-alt',
	'file-archive',
	'file-audio',
	'file-code',
	'file-excel',
	'file-image',
	'file-pdf',
	'file-powerpoint',
	'file-video',
	'file-word',
	'flag',
	'flushed',
	'folder',
	'folder-open',
	'frown',
	'frown-open',
	'futbol',
	'gem',
	'grimace',
	'grin',
	'grin-alt',
	'grin-beam',
	'grin-beam-sweat',
	'grin-hearts',
	'grin-squint',
	'grin-squint-tears',
	'grin-stars',
	'grin-tears',
	'grin-tongue',
	'grin-tongue-squint',
	'grin-tongue-wink',
	'grin-wink',
	'hand-lizard',
	'hand-paper',
	'hand-peace',
	'hand-point-down',
	'hand-point-left',
	'hand-point-right',
	'hand-point-up',
	'hand-pointer',
	'hand-rock',
	'hand-scissors',
	'hand-spock',
	'handshake',
	'hdd',
	'heart',
	'hospital',
	'hourglass',
	'id-badge',
	'id-card',
	'image',
	'images',
	'keyboard',
	'kiss',
	'kiss-beam',
	'kiss-wink-heart',
	'laugh',
	'laugh-beam',
	'laugh-squint',
	'laugh-wink',
	'lemon',
	'life-ring',
	'lightbulb',
	'list-alt',
	'map',
	'meh',
	'meh-blank',
	'meh-rolling-eyes',
	'minus-square',
	'money-bill-alt',
	'moon',
	'newspaper',
	'object-group',
	'object-ungroup',
	'paper-plane',
	'pause-circle',
	'play-circle',
	'plus-square',
	'question-circle',
	'registered',
	'sad-cry',
	'sad-tear',
	'save',
	'share-square',
	'smile',
	'smile-beam',
	'smile-wink',
	'snowflake',
	'square',
	'star',
	'star-half',
	'sticky-note',
	'stop-circle',
	'sun',
	'surprise',
	'thumbs-down',
	'thumbs-up',
	'times-circle',
	'tired',
	'trash-alt',
	'user',
	'user-circle',
	'window-close',
	'window-maximize',
	'window-minimize',
	'window-restore',
];

const FABRANDS = [
	'500px',
	'accessible-icon',
	'accusoft',
	'acquisitions-incorporated',
	'adn',
	'adobe',
	'adversal',
	'affiliatetheme',
	'airbnb',
	'algolia',
	'alipay',
	'amazon',
	'amazon-pay',
	'amilia',
	'android',
	'angellist',
	'angrycreative',
	'angular',
	'app-store',
	'app-store-ios',
	'apper',
	'apple',
	'apple-pay',
	'artstation',
	'asymmetrik',
	'atlassian',
	'audible',
	'autoprefixer',
	'avianex',
	'aviato',
	'aws',
	'bandcamp',
	'battle-net',
	'behance',
	'behance-square',
	'bimobject',
	'bitbucket',
	'bitcoin',
	'bity',
	'black-tie',
	'blackberry',
	'blogger',
	'blogger-b',
	'bluetooth',
	'bluetooth-b',
	'bootstrap',
	'btc',
	'buffer',
	'buromobelexperte',
	'buy-n-large',
	'buysellads',
	'canadian-maple-leaf',
	'cc-amazon-pay',
	'cc-amex',
	'cc-apple-pay',
	'cc-diners-club',
	'cc-discover',
	'cc-jcb',
	'cc-mastercard',
	'cc-paypal',
	'cc-stripe',
	'cc-visa',
	'centercode',
	'centos',
	'chrome',
	'chromecast',
	'cloudscale',
	'cloudsmith',
	'cloudversify',
	'codepen',
	'codiepie',
	'confluence',
	'connectdevelop',
	'contao',
	'cotton-bureau',
	'cpanel',
	'creative-commons',
	'creative-commons-by',
	'creative-commons-nc',
	'creative-commons-nc-eu',
	'creative-commons-nc-jp',
	'creative-commons-nd',
	'creative-commons-pd',
	'creative-commons-pd-alt',
	'creative-commons-remix',
	'creative-commons-sa',
	'creative-commons-sampling',
	'creative-commons-sampling-plus',
	'creative-commons-share',
	'creative-commons-zero',
	'critical-role',
	'css3',
	'css3-alt',
	'cuttlefish',
	'd-and-d',
	'd-and-d-beyond',
	'dailymotion',
	'dashcube',
	'delicious',
	'deploydog',
	'deskpro',
	'dev',
	'deviantart',
	'dhl',
	'diaspora',
	'digg',
	'digital-ocean',
	'discord',
	'discourse',
	'dochub',
	'docker',
	'draft2digital',
	'dribbble',
	'dribbble-square',
	'dropbox',
	'drupal',
	'dyalog',
	'earlybirds',
	'ebay',
	'edge',
	'elementor',
	'ello',
	'ember',
	'empire',
	'envira',
	'erlang',
	'ethereum',
	'etsy',
	'evernote',
	'expeditedssl',
	'facebook',
	'facebook-f',
	'facebook-messenger',
	'facebook-square',
	'fantasy-flight-games',
	'fedex',
	'fedora',
	'figma',
	'firefox',
	'firefox-browser',
	'first-order',
	'first-order-alt',
	'firstdraft',
	'flickr',
	'flipboard',
	'fly',
	'font-awesome',
	'font-awesome-alt',
	'font-awesome-flag',
	'fonticons',
	'fonticons-fi',
	'fort-awesome',
	'fort-awesome-alt',
	'forumbee',
	'foursquare',
	'free-code-camp',
	'freebsd',
	'fulcrum',
	'galactic-republic',
	'galactic-senate',
	'get-pocket',
	'gg',
	'gg-circle',
	'git',
	'git-alt',
	'git-square',
	'github',
	'github-alt',
	'github-square',
	'gitkraken',
	'gitlab',
	'gitter',
	'glide',
	'glide-g',
	'gofore',
	'goodreads',
	'goodreads-g',
	'google',
	'google-drive',
	'google-play',
	'google-plus',
	'google-plus-g',
	'google-plus-square',
	'google-wallet',
	'gratipay',
	'grav',
	'gripfire',
	'grunt',
	'gulp',
	'hacker-news',
	'hacker-news-square',
	'hackerrank',
	'hips',
	'hire-a-helper',
	'hooli',
	'hornbill',
	'hotjar',
	'houzz',
	'html5',
	'hubspot',
	'ideal',
	'imdb',
	'instagram',
	'instagram-square',
	'intercom',
	'internet-explorer',
	'invision',
	'ioxhost',
	'itch-io',
	'itunes',
	'itunes-note',
	'java',
	'jedi-order',
	'jenkins',
	'jira',
	'joget',
	'joomla',
	'js',
	'js-square',
	'jsfiddle',
	'kaggle',
	'keybase',
	'keycdn',
	'kickstarter',
	'kickstarter-k',
	'korvue',
	'laravel',
	'lastfm',
	'lastfm-square',
	'leanpub',
	'less',
	'line',
	'linkedin',
	'linkedin-in',
	'linode',
	'linux',
	'lyft',
	'magento',
	'mailchimp',
	'mandalorian',
	'markdown',
	'mastodon',
	'maxcdn',
	'mdb',
	'medapps',
	'medium',
	'medium-m',
	'medrt',
	'meetup',
	'megaport',
	'mendeley',
	'microblog',
	'microsoft',
	'mix',
	'mixcloud',
	'mixer',
	'mizuni',
	'modx',
	'monero',
	'napster',
	'neos',
	'nimblr',
	'node',
	'node-js',
	'npm',
	'ns8',
	'nutritionix',
	'odnoklassniki',
	'odnoklassniki-square',
	'old-republic',
	'opencart',
	'openid',
	'opera',
	'optin-monster',
	'orcid',
	'osi',
	'page4',
	'pagelines',
	'palfed',
	'patreon',
	'paypal',
	'penny-arcade',
	'periscope',
	'phabricator',
	'phoenix-framework',
	'phoenix-squadron',
	'php',
	'pied-piper',
	'pied-piper-alt',
	'pied-piper-hat',
	'pied-piper-pp',
	'pied-piper-square',
	'pinterest',
	'pinterest-p',
	'pinterest-square',
	'playstation',
	'product-hunt',
	'pushed',
	'python',
	'qq',
	'quinscape',
	'quora',
	'r-project',
	'raspberry-pi',
	'ravelry',
	'react',
	'reacteurope',
	'readme',
	'rebel',
	'red-river',
	'reddit',
	'reddit-alien',
	'reddit-square',
	'redhat',
	'renren',
	'replyd',
	'researchgate',
	'resolving',
	'rev',
	'rocketchat',
	'rockrms',
	'safari',
	'salesforce',
	'sass',
	'schlix',
	'scribd',
	'searchengin',
	'sellcast',
	'sellsy',
	'servicestack',
	'shirtsinbulk',
	'shopify',
	'shopware',
	'simplybuilt',
	'sistrix',
	'sith',
	'sketch',
	'skyatlas',
	'skype',
	'slack',
	'slack-hash',
	'slideshare',
	'snapchat',
	'snapchat-ghost',
	'snapchat-square',
	'soundcloud',
	'sourcetree',
	'speakap',
	'speaker-deck',
	'spotify',
	'squarespace',
	'stack-exchange',
	'stack-overflow',
	'stackpath',
	'staylinked',
	'steam',
	'steam-square',
	'steam-symbol',
	'sticker-mule',
	'strava',
	'stripe',
	'stripe-s',
	'studiovinari',
	'stumbleupon',
	'stumbleupon-circle',
	'superpowers',
	'supple',
	'suse',
	'swift',
	'symfony',
	'teamspeak',
	'telegram',
	'telegram-plane',
	'tencent-weibo',
	'the-red-yeti',
	'themeco',
	'themeisle',
	'think-peaks',
	'trade-federation',
	'trello',
	'tripadvisor',
	'tumblr',
	'tumblr-square',
	'twitch',
	'twitter',
	'twitter-square',
	'typo3',
	'uber',
	'ubuntu',
	'uikit',
	'umbraco',
	'uniregistry',
	'unity',
	'untappd',
	'ups',
	'usb',
	'usps',
	'ussunnah',
	'vaadin',
	'viacoin',
	'viadeo',
	'viadeo-square',
	'viber',
	'vimeo',
	'vimeo-square',
	'vimeo-v',
	'vine',
	'vk',
	'vnv',
	'vuejs',
	'waze',
	'weebly',
	'weibo',
	'weixin',
	'whatsapp',
	'whatsapp-square',
	'whmcs',
	'wikipedia-w',
	'windows',
	'wix',
	'wizards-of-the-coast',
	'wolf-pack-battalion',
	'wordpress',
	'wordpress-simple',
	'wpbeginner',
	'wpexplorer',
	'wpforms',
	'wpressr',
	'xbox',
	'xing',
	'xing-square',
	'y-combinator',
	'yahoo',
	'yammer',
	'yandex',
	'yandex-international',
	'yarn',
	'yelp',
	'yoast',
	'youtube',
	'youtube-square',
	'zhihu',
];

let SOLID = FASOLIDicons.map((name) => {
	return `'fas fa-${name}'`;
});

let REG = FAREG.map((name) => {
	return `'far fa-${name}'`;
});

let BRANDS = FABRANDS.map((name) => {
	return `'fab fa-${name}'`;
});

let FAICONS = [...SOLID, ...REG, ...BRANDS];
console.log(FAICONS.toString());

document.querySelector('body').innerHTML = `${FAICONS}`;

/* const allOLDFAicons = [
	'fab fa-500px',
	'fab fa-accessible-icon',
	'fab fa-accusoft',
	'fas fa-address-book',
	'far fa-address-book',
	'fas fa-address-card',
	'far fa-address-card',
	'fas fa-adjust',
	'fab fa-adn',
	'fab fa-adversal',
	'fab fa-affiliatetheme',
	'fab fa-algolia',
	'fas fa-align-center',
	'fas fa-align-justify',
	'fas fa-align-left',
	'fas fa-align-right',
	'fab fa-amazon',
	'fas fa-ambulance',
	'fas fa-american-sign-language-interpreting',
	'fab fa-amilia',
	'fas fa-anchor',
	'fab fa-android',
	'fab fa-angellist',
	'fas fa-angle-double-down',
	'fas fa-angle-double-left',
	'fas fa-angle-double-right',
	'fas fa-angle-double-up',
	'fas fa-angle-down',
	'fas fa-angle-left',
	'fas fa-angle-right',
	'fas fa-angle-up',
	'fab fa-angrycreative',
	'fab fa-angular',
	'fab fa-app-store',
	'fab fa-app-store-ios',
	'fab fa-apper',
	'fab fa-apple',
	'fab fa-apple-pay',
	'fas fa-archive',
	'fas fa-arrow-alt-circle-down',
	'far fa-arrow-alt-circle-down',
	'fas fa-arrow-alt-circle-left',
	'far fa-arrow-alt-circle-left',
	'fas fa-arrow-alt-circle-right',
	'far fa-arrow-alt-circle-right',
	'fas fa-arrow-alt-circle-up',
	'far fa-arrow-alt-circle-up',
	'fas fa-arrow-circle-down',
	'fas fa-arrow-circle-left',
	'fas fa-arrow-circle-right',
	'fas fa-arrow-circle-up',
	'fas fa-arrow-down',
	'fas fa-arrow-left',
	'fas fa-arrow-right',
	'fas fa-arrow-up',
	'fas fa-arrows-alt',
	'fas fa-arrows-alt-h',
	'fas fa-arrows-alt-v',
	'fas fa-assistive-listening-systems',
	'fas fa-asterisk',
	'fab fa-asymmetrik',
	'fas fa-at',
	'fab fa-audible',
	'fas fa-audio-description',
	'fab fa-autoprefixer',
	'fab fa-avianex',
	'fab fa-aviato',
	'fab fa-aws',
	'fas fa-backward',
	'fas fa-balance-scale',
	'fas fa-ban',
	'fab fa-bandcamp',
	'fas fa-barcode',
	'fas fa-bars',
	'fas fa-bath',
	'fas fa-battery-empty',
	'fas fa-battery-full',
	'fas fa-battery-half',
	'fas fa-battery-quarter',
	'fas fa-battery-three-quarters',
	'fas fa-bed',
	'fas fa-beer',
	'fab fa-behance',
	'fab fa-behance-square',
	'fas fa-bell',
	'far fa-bell',
	'fas fa-bell-slash',
	'far fa-bell-slash',
	'fas fa-bicycle',
	'fab fa-bimobject',
	'fas fa-binoculars',
	'fas fa-birthday-cake',
	'fab fa-bitbucket',
	'fab fa-bitcoin',
	'fab fa-bity',
	'fab fa-black-tie',
	'fab fa-blackberry',
	'fas fa-blind',
	'fab fa-blogger',
	'fab fa-blogger-b',
	'fab fa-bluetooth',
	'fab fa-bluetooth-b',
	'fas fa-bold',
	'fas fa-bolt',
	'fas fa-bomb',
	'fas fa-book',
	'fas fa-bookmark',
	'far fa-bookmark',
	'fas fa-braille',
	'fas fa-briefcase',
	'fab fa-btc',
	'fas fa-bug',
	'fas fa-building',
	'far fa-building',
	'fas fa-bullhorn',
	'fas fa-bullseye',
	'fab fa-buromobelexperte',
	'fas fa-bus',
	'fab fa-buysellads',
	'fas fa-calculator',
	'fas fa-calendar',
	'far fa-calendar',
	'fas fa-calendar-alt',
	'far fa-calendar-alt',
	'fas fa-calendar-check',
	'far fa-calendar-check',
	'fas fa-calendar-minus',
	'far fa-calendar-minus',
	'fas fa-calendar-plus',
	'far fa-calendar-plus',
	'fas fa-calendar-times',
	'far fa-calendar-times',
	'fas fa-camera',
	'fas fa-camera-retro',
	'fas fa-car',
	'fas fa-caret-down',
	'fas fa-caret-left',
	'fas fa-caret-right',
	'fas fa-caret-square-down',
	'far fa-caret-square-down',
	'fas fa-caret-square-left',
	'far fa-caret-square-left',
	'fas fa-caret-square-right',
	'far fa-caret-square-right',
	'fas fa-caret-square-up',
	'far fa-caret-square-up',
	'fas fa-caret-up',
	'fas fa-cart-arrow-down',
	'fas fa-cart-plus',
	'fab fa-cc-amex',
	'fab fa-cc-apple-pay',
	'fab fa-cc-diners-club',
	'fab fa-cc-discover',
	'fab fa-cc-jcb',
	'fab fa-cc-mastercard',
	'fab fa-cc-paypal',
	'fab fa-cc-stripe',
	'fab fa-cc-visa',
	'fab fa-centercode',
	'fas fa-certificate',
	'fas fa-chart-area',
	'fas fa-chart-bar',
	'far fa-chart-bar',
	'fas fa-chart-line',
	'fas fa-chart-pie',
	'fas fa-check',
	'fas fa-check-circle',
	'far fa-check-circle',
	'fas fa-check-square',
	'far fa-check-square',
	'fas fa-chevron-circle-down',
	'fas fa-chevron-circle-left',
	'fas fa-chevron-circle-right',
	'fas fa-chevron-circle-up',
	'fas fa-chevron-down',
	'fas fa-chevron-left',
	'fas fa-chevron-right',
	'fas fa-chevron-up',
	'fas fa-child',
	'fab fa-chrome',
	'fas fa-circle',
	'far fa-circle',
	'fas fa-circle-notch',
	'fas fa-clipboard',
	'far fa-clipboard',
	'fas fa-clock',
	'far fa-clock',
	'fas fa-clone',
	'far fa-clone',
	'fas fa-closed-captioning',
	'far fa-closed-captioning',
	'fas fa-cloud',
	'fas fa-cloud-download-alt',
	'fas fa-cloud-upload-alt',
	'fab fa-cloudscale',
	'fab fa-cloudsmith',
	'fab fa-cloudversify',
	'fas fa-code',
	'fas fa-code-branch',
	'fab fa-codepen',
	'fab fa-codiepie',
	'fas fa-coffee',
	'fas fa-cog',
	'fas fa-cogs',
	'fas fa-columns',
	'fas fa-comment',
	'far fa-comment',
	'fas fa-comment-alt',
	'far fa-comment-alt',
	'fas fa-comments',
	'far fa-comments',
	'fas fa-compass',
	'far fa-compass',
	'fas fa-compress',
	'fab fa-connectdevelop',
	'fab fa-contao',
	'fas fa-copy',
	'far fa-copy',
	'fas fa-copyright',
	'far fa-copyright',
	'fab fa-cpanel',
	'fab fa-creative-commons',
	'fas fa-credit-card',
	'far fa-credit-card',
	'fas fa-crop',
	'fas fa-crosshairs',
	'fab fa-css3',
	'fab fa-css3-alt',
	'fas fa-cube',
	'fas fa-cubes',
	'fas fa-cut',
	'fab fa-cuttlefish',
	'fab fa-d-and-d',
	'fab fa-dashcube',
	'fas fa-database',
	'fas fa-deaf',
	'fab fa-delicious',
	'fab fa-deploydog',
	'fab fa-deskpro',
	'fas fa-desktop',
	'fab fa-deviantart',
	'fab fa-digg',
	'fab fa-digital-ocean',
	'fab fa-discord',
	'fab fa-discourse',
	'fab fa-dochub',
	'fab fa-docker',
	'fas fa-dollar-sign',
	'fas fa-dot-circle',
	'far fa-dot-circle',
	'fas fa-download',
	'fab fa-draft2digital',
	'fab fa-dribbble',
	'fab fa-dribbble-square',
	'fab fa-dropbox',
	'fab fa-drupal',
	'fab fa-dyalog',
	'fab fa-earlybirds',
	'fab fa-edge',
	'fas fa-edit',
	'far fa-edit',
	'fas fa-eject',
	'fas fa-ellipsis-h',
	'fas fa-ellipsis-v',
	'fab fa-ember',
	'fab fa-empire',
	'fas fa-envelope',
	'far fa-envelope',
	'fas fa-envelope-open',
	'far fa-envelope-open',
	'fas fa-envelope-square',
	'fab fa-envira',
	'fas fa-eraser',
	'fab fa-erlang',
	'fab fa-etsy',
	'fas fa-euro-sign',
	'fas fa-exchange-alt',
	'fas fa-exclamation',
	'fas fa-exclamation-circle',
	'fas fa-exclamation-triangle',
	'fas fa-expand',
	'fas fa-expand-arrows-alt',
	'fab fa-expeditedssl',
	'fas fa-external-link-alt',
	'fas fa-external-link-square-alt',
	'fas fa-eye',
	'fas fa-eye-dropper',
	'fas fa-eye-slash',
	'far fa-eye-slash',
	'fab fa-facebook',
	'fab fa-facebook-f',
	'fab fa-facebook-messenger',
	'fab fa-facebook-square',
	'fas fa-fast-backward',
	'fas fa-fast-forward',
	'fas fa-fax',
	'fas fa-female',
	'fas fa-fighter-jet',
	'fas fa-file',
	'far fa-file',
	'fas fa-file-alt',
	'far fa-file-alt',
	'fas fa-file-archive',
	'far fa-file-archive',
	'fas fa-file-audio',
	'far fa-file-audio',
	'fas fa-file-code',
	'far fa-file-code',
	'fas fa-file-excel',
	'far fa-file-excel',
	'fas fa-file-image',
	'far fa-file-image',
	'fas fa-file-pdf',
	'far fa-file-pdf',
	'fas fa-file-powerpoint',
	'far fa-file-powerpoint',
	'fas fa-file-video',
	'far fa-file-video',
	'fas fa-file-word',
	'far fa-file-word',
	'fas fa-film',
	'fas fa-filter',
	'fas fa-fire',
	'fas fa-fire-extinguisher',
	'fab fa-firefox',
	'fab fa-first-order',
	'fab fa-firstdraft',
	'fas fa-flag',
	'far fa-flag',
	'fas fa-flag-checkered',
	'fas fa-flask',
	'fab fa-flickr',
	'fab fa-fly',
	'fas fa-folder',
	'far fa-folder',
	'fas fa-folder-open',
	'far fa-folder-open',
	'fas fa-font',
	'fab fa-font-awesome',
	'fab fa-font-awesome-alt',
	'fab fa-font-awesome-flag',
	'fab fa-fonticons',
	'fab fa-fonticons-fi',
	'fab fa-fort-awesome',
	'fab fa-fort-awesome-alt',
	'fab fa-forumbee',
	'fas fa-forward',
	'fab fa-foursquare',
	'fab fa-free-code-camp',
	'fab fa-freebsd',
	'fas fa-frown',
	'far fa-frown',
	'fas fa-futbol',
	'far fa-futbol',
	'fas fa-gamepad',
	'fas fa-gavel',
	'fas fa-gem',
	'far fa-gem',
	'fas fa-genderless',
	'fab fa-get-pocket',
	'fab fa-gg',
	'fab fa-gg-circle',
	'fas fa-gift',
	'fab fa-git',
	'fab fa-git-square',
	'fab fa-github',
	'fab fa-github-alt',
	'fab fa-github-square',
	'fab fa-gitkraken',
	'fab fa-gitlab',
	'fab fa-gitter',
	'fas fa-glass-martini',
	'fab fa-glide',
	'fab fa-glide-g',
	'fas fa-globe',
	'fab fa-gofore',
	'fab fa-goodreads',
	'fab fa-goodreads-g',
	'fab fa-google',
	'fab fa-google-drive',
	'fab fa-google-play',
	'fab fa-google-plus',
	'fab fa-google-plus-g',
	'fab fa-google-plus-square',
	'fab fa-google-wallet',
	'fas fa-graduation-cap',
	'fab fa-gratipay',
	'fab fa-grav',
	'fab fa-gripfire',
	'fab fa-grunt',
	'fab fa-gulp',
	'fas fa-h-square',
	'fab fa-hacker-news',
	'fab fa-hacker-news-square',
	'fas fa-hand-lizard',
	'far fa-hand-lizard',
	'fas fa-hand-paper',
	'far fa-hand-paper',
	'fas fa-hand-peace',
	'far fa-hand-peace',
	'fas fa-hand-point-down',
	'far fa-hand-point-down',
	'fas fa-hand-point-left',
	'far fa-hand-point-left',
	'fas fa-hand-point-right',
	'far fa-hand-point-right',
	'fas fa-hand-point-up',
	'far fa-hand-point-up',
	'fas fa-hand-pointer',
	'far fa-hand-pointer',
	'fas fa-hand-rock',
	'far fa-hand-rock',
	'fas fa-hand-scissors',
	'far fa-hand-scissors',
	'fas fa-hand-spock',
	'far fa-hand-spock',
	'fas fa-handshake',
	'far fa-handshake',
	'fas fa-hashtag',
	'fas fa-hdd',
	'far fa-hdd',
	'fas fa-heading',
	'fas fa-headphones',
	'fas fa-heart',
	'far fa-heart',
	'fas fa-heartbeat',
	'fab fa-hire-a-helper',
	'fas fa-history',
	'fas fa-home',
	'fab fa-hooli',
	'fas fa-hospital',
	'far fa-hospital',
	'fab fa-hotjar',
	'fas fa-hourglass',
	'far fa-hourglass',
	'fas fa-hourglass-end',
	'fas fa-hourglass-half',
	'fas fa-hourglass-start',
	'fab fa-houzz',
	'fab fa-html5',
	'fab fa-hubspot',
	'fas fa-i-cursor',
	'fas fa-id-badge',
	'far fa-id-badge',
	'fas fa-id-card',
	'far fa-id-card',
	'fas fa-image',
	'far fa-image',
	'fas fa-images',
	'far fa-images',
	'fab fa-imdb',
	'fas fa-inbox',
	'fas fa-indent',
	'fas fa-industry',
	'fas fa-info',
	'fas fa-info-circle',
	'fab fa-instagram',
	'fab fa-internet-explorer',
	'fab fa-ioxhost',
	'fas fa-italic',
	'fab fa-itunes',
	'fab fa-itunes-note',
	'fab fa-jenkins',
	'fab fa-joget',
	'fab fa-joomla',
	'fab fa-js',
	'fab fa-js-square',
	'fab fa-jsfiddle',
	'fas fa-key',
	'fas fa-keyboard',
	'far fa-keyboard',
	'fab fa-keycdn',
	'fab fa-kickstarter',
	'fab fa-kickstarter-k',
	'fas fa-language',
	'fas fa-laptop',
	'fab fa-laravel',
	'fab fa-lastfm',
	'fab fa-lastfm-square',
	'fas fa-leaf',
	'fab fa-leanpub',
	'fas fa-lemon',
	'far fa-lemon',
	'fab fa-less',
	'fas fa-level-down-alt',
	'fas fa-level-up-alt',
	'fas fa-life-ring',
	'far fa-life-ring',
	'fas fa-lightbulb',
	'far fa-lightbulb',
	'fab fa-line',
	'fas fa-link',
	'fab fa-linkedin',
	'fab fa-linkedin-in',
	'fab fa-linode',
	'fab fa-linux',
	'fas fa-lira-sign',
	'fas fa-list',
	'fas fa-list-alt',
	'far fa-list-alt',
	'fas fa-list-ol',
	'fas fa-list-ul',
	'fas fa-location-arrow',
	'fas fa-lock',
	'fas fa-lock-open',
	'fas fa-long-arrow-alt-down',
	'fas fa-long-arrow-alt-left',
	'fas fa-long-arrow-alt-right',
	'fas fa-long-arrow-alt-up',
	'fas fa-low-vision',
	'fab fa-lyft',
	'fab fa-magento',
	'fas fa-magic',
	'fas fa-magnet',
	'fas fa-male',
	'fas fa-map',
	'far fa-map',
	'fas fa-map-marker',
	'fas fa-map-marker-alt',
	'fas fa-map-pin',
	'fas fa-map-signs',
	'fas fa-mars',
	'fas fa-mars-double',
	'fas fa-mars-stroke',
	'fas fa-mars-stroke-h',
	'fas fa-mars-stroke-v',
	'fab fa-maxcdn',
	'fab fa-medapps',
	'fab fa-medium',
	'fab fa-medium-m',
	'fas fa-medkit',
	'fab fa-medrt',
	'fab fa-meetup',
	'fas fa-meh',
	'far fa-meh',
	'fas fa-mercury',
	'fas fa-microchip',
	'fas fa-microphone',
	'fas fa-microphone-slash',
	'fab fa-microsoft',
	'fas fa-minus',
	'fas fa-minus-circle',
	'fas fa-minus-square',
	'far fa-minus-square',
	'fab fa-mix',
	'fab fa-mixcloud',
	'fab fa-mizuni',
	'fas fa-mobile',
	'fas fa-mobile-alt',
	'fab fa-modx',
	'fab fa-monero',
	'fas fa-money-bill-alt',
	'far fa-money-bill-alt',
	'fas fa-moon',
	'far fa-moon',
	'fas fa-motorcycle',
	'fas fa-mouse-pointer',
	'fas fa-music',
	'fab fa-napster',
	'fas fa-neuter',
	'fas fa-newspaper',
	'far fa-newspaper',
	'fab fa-node',
	'fab fa-node-js',
	'fab fa-npm',
	'fab fa-ns8',
	'fab fa-nutritionix',
	'fas fa-object-group',
	'far fa-object-group',
	'fas fa-object-ungroup',
	'far fa-object-ungroup',
	'fab fa-odnoklassniki',
	'fab fa-odnoklassniki-square',
	'fab fa-opencart',
	'fab fa-openid',
	'fab fa-opera',
	'fab fa-optin-monster',
	'fab fa-osi',
	'fas fa-outdent',
	'fab fa-page4',
	'fab fa-pagelines',
	'fas fa-paint-brush',
	'fab fa-palfed',
	'fas fa-paper-plane',
	'far fa-paper-plane',
	'fas fa-paperclip',
	'fas fa-paragraph',
	'fas fa-paste',
	'fab fa-patreon',
	'fas fa-pause',
	'fas fa-pause-circle',
	'far fa-pause-circle',
	'fas fa-paw',
	'fab fa-paypal',
	'fas fa-pen-square',
	'fas fa-pencil-alt',
	'fas fa-percent',
	'fab fa-periscope',
	'fab fa-phabricator',
	'fab fa-phoenix-framework',
	'fas fa-phone',
	'fas fa-phone-square',
	'fas fa-phone-volume',
	'fab fa-pied-piper',
	'fab fa-pied-piper-alt',
	'fab fa-pied-piper-pp',
	'fab fa-pinterest',
	'fab fa-pinterest-p',
	'fab fa-pinterest-square',
	'fas fa-plane',
	'fas fa-play',
	'fas fa-play-circle',
	'far fa-play-circle',
	'fab fa-playstation',
	'fas fa-plug',
	'fas fa-plus',
	'fas fa-plus-circle',
	'fas fa-plus-square',
	'far fa-plus-square',
	'fas fa-podcast',
	'fas fa-pound-sign',
	'fas fa-power-off',
	'fas fa-print',
	'fab fa-product-hunt',
	'fab fa-pushed',
	'fas fa-puzzle-piece',
	'fab fa-python',
	'fab fa-qq',
	'fas fa-qrcode',
	'fas fa-question',
	'fas fa-question-circle',
	'far fa-question-circle',
	'fab fa-quora',
	'fas fa-quote-left',
	'fas fa-quote-right',
	'fas fa-random',
	'fab fa-ravelry',
	'fab fa-react',
	'fab fa-rebel',
	'fas fa-recycle',
	'fab fa-red-river',
	'fab fa-reddit',
	'fab fa-reddit-alien',
	'fab fa-reddit-square',
	'fas fa-redo',
	'fas fa-redo-alt',
	'fas fa-registered',
	'far fa-registered',
	'fab fa-renren',
	'fas fa-reply',
	'fas fa-reply-all',
	'fab fa-replyd',
	'fab fa-resolving',
	'fas fa-retweet',
	'fas fa-road',
	'fas fa-rocket',
	'fab fa-rocketchat',
	'fab fa-rockrms',
	'fas fa-rss',
	'fas fa-rss-square',
	'fas fa-ruble-sign',
	'fas fa-rupee-sign',
	'fab fa-safari',
	'fab fa-sass',
	'fas fa-save',
	'far fa-save',
	'fab fa-schlix',
	'fab fa-scribd',
	'fas fa-search',
	'fas fa-search-minus',
	'fas fa-search-plus',
	'fab fa-searchengin',
	'fab fa-sellcast',
	'fab fa-sellsy',
	'fas fa-server',
	'fab fa-servicestack',
	'fas fa-share',
	'fas fa-share-alt',
	'fas fa-share-alt-square',
	'fas fa-share-square',
	'far fa-share-square',
	'fas fa-shekel-sign',
	'fas fa-shield-alt',
	'fas fa-ship',
	'fab fa-shirtsinbulk',
	'fas fa-shopping-bag',
	'fas fa-shopping-basket',
	'fas fa-shopping-cart',
	'fas fa-shower',
	'fas fa-sign-in-alt',
	'fas fa-sign-language',
	'fas fa-sign-out-alt',
	'fas fa-signal',
	'fab fa-simplybuilt',
	'fab fa-sistrix',
	'fas fa-sitemap',
	'fab fa-skyatlas',
	'fab fa-skype',
	'fab fa-slack',
	'fab fa-slack-hash',
	'fas fa-sliders-h',
	'fab fa-slideshare',
	'fas fa-smile',
	'far fa-smile',
	'fab fa-snapchat',
	'fab fa-snapchat-ghost',
	'fab fa-snapchat-square',
	'fas fa-snowflake',
	'far fa-snowflake',
	'fas fa-sort',
	'fas fa-sort-alpha-down',
	'fas fa-sort-alpha-up',
	'fas fa-sort-amount-down',
	'fas fa-sort-amount-up',
	'fas fa-sort-down',
	'fas fa-sort-numeric-down',
	'fas fa-sort-numeric-up',
	'fas fa-sort-up',
	'fab fa-soundcloud',
	'fas fa-space-shuttle',
	'fab fa-speakap',
	'fas fa-spinner',
	'fab fa-spotify',
	'fas fa-square',
	'far fa-square',
	'fab fa-stack-exchange',
	'fab fa-stack-overflow',
	'fas fa-star',
	'far fa-star',
	'fas fa-star-half',
	'far fa-star-half',
	'fab fa-staylinked',
	'fab fa-steam',
	'fab fa-steam-square',
	'fab fa-steam-symbol',
	'fas fa-step-backward',
	'fas fa-step-forward',
	'fas fa-stethoscope',
	'fab fa-sticker-mule',
	'fas fa-sticky-note',
	'far fa-sticky-note',
	'fas fa-stop',
	'fas fa-stop-circle',
	'far fa-stop-circle',
	'fab fa-strava',
	'fas fa-street-view',
	'fas fa-strikethrough',
	'fab fa-stripe',
	'fab fa-stripe-s',
	'fab fa-studiovinari',
	'fab fa-stumbleupon',
	'fab fa-stumbleupon-circle',
	'fas fa-subscript',
	'fas fa-subway',
	'fas fa-suitcase',
	'fas fa-sun',
	'far fa-sun',
	'fab fa-superpowers',
	'fas fa-superscript',
	'fab fa-supple',
	'fas fa-sync',
	'fas fa-sync-alt',
	'fas fa-table',
	'fas fa-tablet',
	'fas fa-tablet-alt',
	'fas fa-tachometer-alt',
	'fas fa-tag',
	'fas fa-tags',
	'fas fa-tasks',
	'fas fa-taxi',
	'fab fa-telegram',
	'fab fa-telegram-plane',
	'fab fa-tencent-weibo',
	'fas fa-terminal',
	'fas fa-text-height',
	'fas fa-text-width',
	'fas fa-th',
	'fas fa-th-large',
	'fas fa-th-list',
	'fab fa-themeisle',
	'fas fa-thermometer-empty',
	'fas fa-thermometer-full',
	'fas fa-thermometer-half',
	'fas fa-thermometer-quarter',
	'fas fa-thermometer-three-quarters',
	'fas fa-thumbs-down',
	'far fa-thumbs-down',
	'fas fa-thumbs-up',
	'far fa-thumbs-up',
	'fas fa-thumbtack',
	'fas fa-ticket-alt',
	'fas fa-times',
	'fas fa-times-circle',
	'far fa-times-circle',
	'fas fa-tint',
	'fas fa-toggle-off',
	'fas fa-toggle-on',
	'fas fa-trademark',
	'fas fa-train',
	'fas fa-transgender',
	'fas fa-transgender-alt',
	'fas fa-trash',
	'fas fa-trash-alt',
	'far fa-trash-alt',
	'fas fa-tree',
	'fab fa-trello',
	'fab fa-tripadvisor',
	'fas fa-trophy',
	'fas fa-truck',
	'fas fa-tty',
	'fab fa-tumblr',
	'fab fa-tumblr-square',
	'fas fa-tv',
	'fab fa-twitch',
	'fab fa-twitter',
	'fab fa-twitter-square',
	'fab fa-typo3',
	'fab fa-uber',
	'fab fa-uikit',
	'fas fa-umbrella',
	'fas fa-underline',
	'fas fa-undo',
	'fas fa-undo-alt',
	'fab fa-uniregistry',
	'fas fa-universal-access',
	'fas fa-university',
	'fas fa-unlink',
	'fas fa-unlock',
	'fas fa-unlock-alt',
	'fab fa-untappd',
	'fas fa-upload',
	'fab fa-usb',
	'fas fa-user',
	'far fa-user',
	'fas fa-user-circle',
	'far fa-user-circle',
	'fas fa-user-md',
	'fas fa-user-plus',
	'fas fa-user-secret',
	'fas fa-user-times',
	'fas fa-users',
	'fab fa-ussunnah',
	'fas fa-utensil-spoon',
	'fas fa-utensils',
	'fab fa-vaadin',
	'fas fa-venus',
	'fas fa-venus-double',
	'fas fa-venus-mars',
	'fab fa-viacoin',
	'fab fa-viadeo',
	'fab fa-viadeo-square',
	'fab fa-viber',
	'fas fa-video',
	'fab fa-vimeo',
	'fab fa-vimeo-square',
	'fab fa-vimeo-v',
	'fab fa-vine',
	'fab fa-vk',
	'fab fa-vnv',
	'fas fa-volume-down',
	'fas fa-volume-off',
	'fas fa-volume-up',
	'fab fa-vuejs',
	'fab fa-weibo',
	'fab fa-weixin',
	'fab fa-whatsapp',
	'fab fa-whatsapp-square',
	'fas fa-wheelchair',
	'fab fa-whmcs',
	'fas fa-wifi',
	'fab fa-wikipedia-w',
	'fas fa-window-close',
	'far fa-window-close',
	'fas fa-window-maximize',
	'far fa-window-maximize',
	'fas fa-window-minimize',
	'fas fa-window-restore',
	'far fa-window-restore',
	'fab fa-windows',
	'fas fa-won-sign',
	'fab fa-wordpress',
	'fab fa-wordpress-simple',
	'fab fa-wpbeginner',
	'fab fa-wpexplorer',
	'fab fa-wpforms',
	'fas fa-wrench',
	'fab fa-xbox',
	'fab fa-xing',
	'fab fa-xing-square',
	'fab fa-y-combinator',
	'fab fa-yahoo',
	'fab fa-yandex',
	'fab fa-yandex-international',
	'fab fa-yelp',
	'fas fa-yen-sign',
	'fab fa-yoast',
	'fab fa-youtube',
];

const allMaticons = [
	'access_alarm',
	'3d_rotation',
	'access_alarms',
	'access_time',
	'accessibility',
	'account_balance',
	'account_balance_wallet',
	'account_box',
	'account_circle',
	'adb',
	'add',
	'add_alarm',
	'add_alert',
	'add_box',
	'add_circle',
	'add_circle_outline',
	'add_shopping_cart',
	'add_to_photos',
	'adjust',
	'airline_seat_flat',
	'airline_seat_flat_angled',
	'airline_seat_individual_suite',
	'airline_seat_legroom_extra',
	'airline_seat_legroom_normal',
	'airline_seat_legroom_reduced',
	'airline_seat_recline_extra',
	'airline_seat_recline_normal',
	'airplanemode_active',
	'airplanemode_inactive',
	'airplay',
	'alarm',
	'alarm_add',
	'alarm_off',
	'alarm_on',
	'album',
	'android',
	'announcement',
	'apps',
	'archive',
	'arrow_back',
	'arrow_drop_down',
	'arrow_drop_down_circle',
	'arrow_drop_up',
	'arrow_forward',
	'aspect_ratio',
	'assessment',
	'assignment',
	'assignment_ind',
	'assignment_late',
	'assignment_return',
	'assignment_returned',
	'assignment_turned_in',
	'assistant',
	'assistant_photo',
	'attach_file',
	'attach_money',
	'attachment',
	'audiotrack',
	'autorenew',
	'av_timer',
	'backspace',
	'backup',
	'battery_alert',
	'battery_charging_full',
	'battery_full',
	'battery_std',
	'battery_unknown',
	'beenhere',
	'block',
	'bluetooth',
	'bluetooth_audio',
	'bluetooth_connected',
	'bluetooth_disabled',
	'bluetooth_searching',
	'blur_circular',
	'blur_linear',
	'blur_off',
	'blur_on',
	'book',
	'bookmark',
	'bookmark_border',
	'border_all',
	'border_bottom',
	'border_clear',
	'border_color',
	'border_horizontal',
	'border_inner',
	'border_left',
	'border_outer',
	'border_right',
	'border_style',
	'border_top',
	'border_vertical',
	'brightness_1',
	'brightness_2',
	'brightness_3',
	'brightness_4',
	'brightness_5',
	'brightness_6',
	'brightness_7',
	'brightness_auto',
	'brightness_high',
	'brightness_low',
	'brightness_medium',
	'broken_image',
	'brush',
	'bug_report',
	'build',
	'business',
	'cached',
	'cake',
	'call',
	'call_end',
	'call_made',
	'call_merge',
	'call_missed',
	'call_received',
	'call_split',
	'camera',
	'camera_alt',
	'camera_enhance',
	'camera_front',
	'camera_rear',
	'camera_roll',
	'cancel',
	'card_giftcard',
	'card_membership',
	'card_travel',
	'cast',
	'cast_connected',
	'center_focus_strong',
	'center_focus_weak',
	'change_history',
	'chat',
	'chat_bubble',
	'chat_bubble_outline',
	'check',
	'check_box',
	'check_box_outline_blank',
	'check_circle',
	'chevron_left',
	'chevron_right',
	'chrome_reader_mode',
	'class',
	'clear',
	'clear_all',
	'close',
	'closed_caption',
	'cloud',
	'cloud_circle',
	'cloud_done',
	'cloud_download',
	'cloud_off',
	'cloud_queue',
	'cloud_upload',
	'code',
	'collections',
	'collections_bookmark',
	'color_lens',
	'colorize',
	'comment',
	'compare',
	'computer',
	'confirmation_number',
	'contact_phone',
	'contacts',
	'content_copy',
	'content_cut',
	'content_paste',
	'control_point',
	'control_point_duplicate',
	'create',
	'credit_card',
	'crop',
	'crop_16_9',
	'crop_3_2',
	'crop_5_4',
	'crop_7_5',
	'crop_din',
	'crop_free',
	'crop_landscape',
	'crop_original',
	'crop_portrait',
	'crop_square',
	'dashboard',
	'data_usage',
	'dehaze',
	'delete',
	'description',
	'desktop_mac',
	'desktop_windows',
	'details',
	'developer_board',
	'developer_mode',
	'device_hub',
	'devices',
	'dialer_sip',
	'dialpad',
	'directions',
	'directions_bike',
	'directions_boat',
	'directions_bus',
	'directions_car',
	'directions_railway',
	'directions_run',
	'directions_subway',
	'directions_transit',
	'directions_walk',
	'disc_full',
	'dns',
	'do_not_disturb',
	'do_not_disturb_alt',
	'dock',
	'domain',
	'done',
	'done_all',
	'drafts',
	'drive_eta',
	'dvr',
	'edit',
	'eject',
	'email',
	'equalizer',
	'error',
	'error_outline',
	'event',
	'event_available',
	'event_busy',
	'event_note',
	'event_seat',
	'exit_to_app',
	'expand_less',
	'expand_more',
	'explicit',
	'explore',
	'exposure',
	'exposure_neg_1',
	'exposure_neg_2',
	'exposure_plus_1',
	'exposure_plus_2',
	'exposure_zero',
	'extension',
	'face',
	'fast_forward',
	'fast_rewind',
	'favorite',
	'favorite_border',
	'feedback',
	'file_download',
	'file_upload',
	'filter',
	'filter_1',
	'filter_2',
	'filter_3',
	'filter_4',
	'filter_5',
	'filter_6',
	'filter_7',
	'filter_8',
	'filter_9',
	'filter_9_plus',
	'filter_b_and_w',
	'filter_center_focus',
	'filter_drama',
	'filter_frames',
	'filter_hdr',
	'filter_list',
	'filter_none',
	'filter_tilt_shift',
	'filter_vintage',
	'find_in_page',
	'find_replace',
	'flag',
	'flare',
	'flash_auto',
	'flash_off',
	'flash_on',
	'flight',
	'flight_land',
	'flight_takeoff',
	'flip',
	'flip_to_back',
	'flip_to_front',
	'folder',
	'folder_open',
	'folder_shared',
	'folder_special',
	'font_download',
	'format_align_center',
	'format_align_justify',
	'format_align_left',
	'format_align_right',
	'format_bold',
	'format_clear',
	'format_color_fill',
	'format_color_reset',
	'format_color_text',
	'format_indent_decrease',
	'format_indent_increase',
	'format_italic',
	'format_line_spacing',
	'format_list_bulleted',
	'format_list_numbered',
	'format_paint',
	'format_quote',
	'format_size',
	'format_strikethrough',
	'format_textdirection_l_to_r',
	'format_textdirection_r_to_l',
	'format_underlined',
	'forum',
	'forward',
	'forward_10',
	'forward_30',
	'forward_5',
	'fullscreen',
	'fullscreen_exit',
	'functions',
	'gamepad',
	'games',
	'gesture',
	'get_app',
	'gif',
	'gps_fixed',
	'gps_not_fixed',
	'gps_off',
	'grade',
	'gradient',
	'grain',
	'graphic_eq',
	'grid_off',
	'grid_on',
	'group',
	'group_add',
	'group_work',
	'hd',
	'hdr_off',
	'hdr_on',
	'hdr_strong',
	'hdr_weak',
	'headset',
	'headset_mic',
	'healing',
	'hearing',
	'help',
	'help_outline',
	'high_quality',
	'highlight_off',
	'history',
	'home',
	'hotel',
	'hourglass_empty',
	'hourglass_full',
	'http',
	'https',
	'image',
	'image_aspect_ratio',
	'import_export',
	'inbox',
	'indeterminate_check_box',
	'info',
	'info_outline',
	'input',
	'insert_chart',
	'insert_comment',
	'insert_drive_file',
	'insert_emoticon',
	'insert_invitation',
	'insert_link',
	'insert_photo',
	'invert_colors',
	'invert_colors_off',
	'iso',
	'keyboard',
	'keyboard_arrow_down',
	'keyboard_arrow_left',
	'keyboard_arrow_right',
	'keyboard_arrow_up',
	'keyboard_backspace',
	'keyboard_capslock',
	'keyboard_hide',
	'keyboard_return',
	'keyboard_tab',
	'keyboard_voice',
	'label',
	'label_outline',
	'landscape',
	'language',
	'laptop',
	'laptop_chromebook',
	'laptop_mac',
	'laptop_windows',
	'launch',
	'layers',
	'layers_clear',
	'leak_add',
	'leak_remove',
	'lens',
	'library_add',
	'library_books',
	'library_music',
	'link',
	'list',
	'live_help',
	'live_tv',
	'local_activity',
	'local_airport',
	'local_atm',
	'local_bar',
	'local_cafe',
	'local_car_wash',
	'local_convenience_store',
	'local_dining',
	'local_drink',
	'local_florist',
	'local_gas_station',
	'local_grocery_store',
	'local_hospital',
	'local_hotel',
	'local_laundry_service',
	'local_library',
	'local_mall',
	'local_movies',
	'local_offer',
	'local_parking',
	'local_pharmacy',
	'local_phone',
	'local_pizza',
	'local_play',
	'local_post_office',
	'local_printshop',
	'local_see',
	'local_shipping',
	'local_taxi',
	'location_city',
	'location_disabled',
	'location_off',
	'location_on',
	'location_searching',
	'lock',
	'lock_open',
	'lock_outline',
	'looks',
	'looks_3',
	'looks_4',
	'looks_5',
	'looks_6',
	'looks_one',
	'looks_two',
	'loop',
	'loupe',
	'loyalty',
	'mail',
	'map',
	'markunread',
	'markunread_mailbox',
	'memory',
	'menu',
	'merge_type',
	'message',
	'mic',
	'mic_none',
	'mic_off',
	'mms',
	'mode_comment',
	'money_off',
	'monochrome_photos',
	'mood',
	'mood_bad',
	'more',
	'more_horiz',
	'more_vert',
	'mouse',
	'movie',
	'movie_creation',
	'music_note',
	'my_location',
	'nature',
	'nature_people',
	'navigate_before',
	'navigate_next',
	'navigation',
	'network_cell',
	'network_locked',
	'network_wifi',
	'new_releases',
	'nfc',
	'no_sim',
	'not_interested',
	'note_add',
	'notifications',
	'notifications_active',
	'notifications_none',
	'notifications_off',
	'notifications_paused',
	'offline_pin',
	'ondemand_video',
	'open_in_browser',
	'open_in_new',
	'open_with',
	'pages',
	'pageview',
	'palette',
	'panorama',
	'panorama_fish_eye',
	'panorama_horizontal',
	'panorama_vertical',
	'panorama_wide_angle',
	'party_mode',
	'pause',
	'pause_circle_filled',
	'pause_circle_outline',
	'payment',
	'people',
	'people_outline',
	'perm_camera_mic',
	'perm_contact_calendar',
	'perm_data_setting',
	'perm_device_information',
	'perm_identity',
	'perm_media',
	'perm_phone_msg',
	'perm_scan_wifi',
	'person',
	'person_add',
	'person_outline',
	'person_pin',
	'personal_video',
	'phone',
	'phone_android',
	'phone_bluetooth_speaker',
	'phone_forwarded',
	'phone_in_talk',
	'phone_iphone',
	'phone_locked',
	'phone_missed',
	'phone_paused',
	'phonelink',
	'phonelink_erase',
	'phonelink_lock',
	'phonelink_off',
	'phonelink_ring',
	'phonelink_setup',
	'photo',
	'photo_album',
	'photo_camera',
	'photo_library',
	'photo_size_select_actual',
	'photo_size_select_large',
	'photo_size_select_small',
	'picture_as_pdf',
	'picture_in_picture',
	'pin_drop',
	'place',
	'play_arrow',
	'play_circle_filled',
	'play_circle_outline',
	'play_for_work',
	'playlist_add',
	'plus_one',
	'poll',
	'polymer',
	'portable_wifi_off',
	'portrait',
	'power',
	'power_input',
	'power_settings_new',
	'present_to_all',
	'print',
	'public',
	'publish',
	'query_builder',
	'question_answer',
	'queue',
	'queue_music',
	'radio',
	'radio_button_checked',
	'radio_button_unchecked',
	'rate_review',
	'receipt',
	'recent_actors',
	'redeem',
	'redo',
	'refresh',
	'remove',
	'remove_circle',
	'remove_circle_outline',
	'remove_red_eye',
	'reorder',
	'repeat',
	'repeat_one',
	'replay',
	'replay_10',
	'replay_30',
	'replay_5',
	'reply',
	'reply_all',
	'report',
	'report_problem',
	'restaurant_menu',
	'restore',
	'ring_volume',
	'room',
	'rotate_90_degrees_ccw',
	'rotate_left',
	'rotate_right',
	'router',
	'satellite',
	'save',
	'scanner',
	'schedule',
	'school',
	'screen_lock_landscape',
	'screen_lock_portrait',
	'screen_lock_rotation',
	'screen_rotation',
	'sd_card',
	'sd_storage',
	'search',
	'security',
	'select_all',
	'send',
	'settings',
	'settings_applications',
	'settings_backup_restore',
	'settings_bluetooth',
	'settings_brightness',
	'settings_cell',
	'settings_ethernet',
	'settings_input_antenna',
	'settings_input_component',
	'settings_input_composite',
	'settings_input_hdmi',
	'settings_input_svideo',
	'settings_overscan',
	'settings_phone',
	'settings_power',
	'settings_remote',
	'settings_system_daydream',
	'settings_voice',
	'share',
	'shop',
	'shop_two',
	'shopping_basket',
	'shopping_cart',
	'shuffle',
	'signal_cellular_4_bar',
	'signal_cellular_connected_no_internet_4_bar',
	'signal_cellular_no_sim',
	'signal_cellular_null',
	'signal_cellular_off',
	'signal_wifi_4_bar',
	'signal_wifi_4_bar_lock',
	'signal_wifi_off',
	'sim_card',
	'sim_card_alert',
	'skip_next',
	'skip_previous',
	'slideshow',
	'smartphone',
	'sms',
	'sms_failed',
	'snooze',
	'sort',
	'sort_by_alpha',
	'space_bar',
	'speaker',
	'speaker_group',
	'speaker_notes',
	'speaker_phone',
	'spellcheck',
	'star',
	'star_border',
	'star_half',
	'stars',
	'stay_current_landscape',
	'stay_current_portrait',
	'stay_primary_landscape',
	'stay_primary_portrait',
	'stop',
	'storage',
	'store',
	'store_mall_directory',
	'straighten',
	'strikethrough_s',
	'style',
	'subject',
	'subtitles',
	'supervisor_account',
	'surround_sound',
	'swap_calls',
	'swap_horiz',
	'swap_vert',
	'swap_vertical_circle',
	'switch_camera',
	'switch_video',
	'sync',
	'sync_disabled',
	'sync_problem',
	'system_update',
	'system_update_alt',
	'tab',
	'tab_unselected',
	'tablet',
	'tablet_android',
	'tablet_mac',
	'tag_faces',
	'tap_and_play',
	'terrain',
	'text_format',
	'textsms',
	'texture',
	'theaters',
	'thumb_down',
	'thumb_up',
	'thumbs_up_down',
	'time_to_leave',
	'timelapse',
	'timer',
	'timer_10',
	'timer_3',
	'timer_off',
	'toc',
	'today',
	'toll',
	'tonality',
	'toys',
	'track_changes',
	'traffic',
	'transform',
	'translate',
	'trending_down',
	'trending_flat',
	'trending_up',
	'tune',
	'turned_in',
	'turned_in_not',
	'tv',
	'undo',
	'unfold_less',
	'unfold_more',
	'usb',
	'verified_user',
	'vertical_align_bottom',
	'vertical_align_center',
	'vertical_align_top',
	'vibration',
	'video_library',
	'videocam',
	'videocam_off',
	'view_agenda',
	'view_array',
	'view_carousel',
	'view_column',
	'view_comfy',
	'view_compact',
	'view_day',
	'view_headline',
	'view_list',
	'view_module',
	'view_quilt',
	'view_stream',
	'view_week',
	'vignette',
	'visibility',
	'visibility_off',
	'voice_chat',
	'voicemail',
	'volume_down',
	'volume_mute',
	'volume_off',
	'volume_up',
	'vpn_key',
	'vpn_lock',
	'wallpaper',
	'warning',
	'watch',
	'wb_auto',
	'wb_cloudy',
	'wb_incandescent',
	'wb_iridescent',
	'wb_sunny',
	'wc',
	'web',
	'whatshot',
	'widgets',
	'wifi',
	'wifi_lock',
	'wifi_tethering',
	'work',
	'wrap_text',
	'youtube_searched_for',
	'zoom_in',
	'zoom_out',
];
 */
